### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs-ko#1]
Welcome, new localizations team :)

To get this team up and running you have a few initial tasks to accomplish:
- Create a README.md for this repository, it should include:
  - A "call to action" pointing to the Issue tracker for new translators to find tasks.
  - A list of the team members.
  - Instructions on how to log an issue to be added to this team.
- Set the repository description. This should not be in English, it should be in the language for this community :)
- Social Media
  - Create a twitter account for this language. Share the password privately with the team.
  - Create accounts on other social media popular in this language. Share the passwords private with the rest of the team.
  - Make sure you use these accounts not just to promote newly translated material but also to attract people in your community to help with translation tasks.
- _Optional:_ If you plan to do a Google hangout w/ your localization team have @mikeal add you to the Google+ account so that it can post to the `iojs` YouTube channel. Once you are added there is [documentation on how to setup a hangout-on-air](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).
- Finally, create a new Issue to translate and publish the [latest io.js post](https://medium.com/@iojs). Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

**Comment by taggon** [comment]
@mikeal Are we allowed to translate and publish good articles which are linked by Twitter @official_iojs? For example, I think the story about [building 27 localization teams in a single day](https://medium.com/@mikeal/how-io-js-built-a-146-person-27-language-localization-effort-in-one-day-65e5b1c49a62) (yes, it's yours) can make a good impression to the Korean community.

**Comment by mikeal** [comment]
You are "allowed" to do whatever you like of you think it will be
beneficial to your community. Go for
it! :)

**Comment by taggon** [comment]
@mikeal Thanks for your prompt response!

**Comment by outsideris** [comment]
@mikeal Some accident has been happened.
One of us deleted our repository by mistake. Github team restore it, but this repository is not under our team, [iojs-kr](https://github.com/orgs/iojs/teams/iojs-kr).
So, could you reassign this repository to iojs-kr team?

Also, we want to make people to contibute this localization. Therefore, we want to invite more people as our team members, but we don't want to give admin access to all of them.
Could you please makke another team for us, such like `iojs-kr-translators`. If so, we only set write access on it and invite more people from our community. 

We apologize about that.

**Comment by mikeal** [comment]
Created https://github.com/orgs/iojs/teams/iojs-kr-translators and added to this repo :)

**Comment by outsideris** [comment]
@mikeal I can't access `iojs-kr-translators`. Please add me to it with admin access. I will invite others.

**Comment by marocchino** [comment]
@mikeal I can't see it too. Is the repository assigned properly?

**Comment by mikeal** [comment]
you know what, you have to be an org owner in order to do that.

i just signed up for a GH beta of new org permissions so maybe in the next few days i'll have a better way to handle this.

**Comment by outsideris** [comment]
@mikeal We didn't ask admin access for iojs. We just asked permissions to access `iojs-kr-translators`.
None of us can access it. 
BTW, GH beta of new org permissions is very interesting.

**Comment by mikeal** [comment]
@outsideris I know, I'm saying that I don't think you can add people to that group unless you are. GitHub permissions are strange, each _group_ has a permission level (read/write/admin) so if we make a group that is _not_ admin then the members don't have the right to add more people to it which means you have to be an org owner in order to continue to add people to it.

**Comment by outsideris** [comment]
@mikeal I got it. We was curious about that. We read the documents but it was not clear.
We understand what you mean. We will consider the way contributors get involved in our community.
Really thanks.

**Comment by marocchino** [comment]
It looks done. :)
