### ISSUE TITLE
Re-activate twitter account

### ISSUE THREAD

**Issue by AkiaCode** [nodejs/nodejs-ko#1045]
![image](https://user-images.githubusercontent.com/71239005/103767208-919e7f00-5063-11eb-9582-929d88008448.png)

저 트위터로 통해 이동 해보니 
![image](https://user-images.githubusercontent.com/71239005/103767343-c8749500-5063-11eb-9391-2db10cdafea7.png)

라고 삭제되어 있는 데 저기 사진에 있는 설명을 삭제하는 건 어떤가요?

트위터 링크: https://twitter.com/nodejs_ko

**Comment by yous** [comment]
앗 계정이 정지된 상태였군요. 혹시 문제 확인 가능한 분 계실까요? @nodejs/nodejs-ko

**Comment by outsideris** [comment]
앗! 글은 자동으로 나가는 거지만 저도 종종 들어가 보던 계정이었는데 정지된지 몰랐네요. 11월까지는 글이 올라간거 보면 12월 중에 정지된 것 같네요. 
<img width="872" alt="스크린샷 2021-01-07 오후 10 45 34" src="https://user-images.githubusercontent.com/390146/103902343-bc5d0600-513d-11eb-8271-6f0993e27cdd.png">

딱히 이상한 글도 없는데 그렇군요. 

https://help.twitter.com/ko/managing-your-account/suspended-twitter-accounts 를 보고 이의 제기를 일단 제 메일로 접수해 놨습니다. 
저 트위터 계정에 등록된 이메일(`g*****9+iojs@gmail.com`)은  @taggon 님 메일인것 같은데 메일에 혹시 일시정지 관련 안내가 있는지 확인 부탁드리겠습니다.

**Comment by taggon** [comment]
@outsideris @yous 메일함을 살펴봤는데 저에게 메일이 온 건 없었습니다. 혹시 제가 해야하는 일이 있으면 말씀해주세요.

**Comment by outsideris** [comment]
메일 보내놓고 아직 답변 못받았는데 추가로 필요한 부분 있으면 말씀드릴께요

**Comment by outsideris** [comment]
반응이 없어서 다시 들어가서 좀 둘러봤는데요. 

https://help.twitter.com/en/managing-your-account/locked-and-limited-accounts 이 문서를 보고 하다가 @taggon 님 메일로 비번 변경 메일을 보냈습니다. 환번 확인 부탁드립니다. (저번엔 몰랐는데 여기 보니 보안 이슈로 정지되는 경우도 있는것 같네요)

**Comment by taggon** [comment]
결국 복구된 것 같습니다. 재활성화 요청하고 오픈소스 관련 어카운트라고 알리고 나니까 별도 공지없이 계정이 돌아왔습니다. 밀렸던 트윗이 한꺼번에 올라왔고요. 안내가 제대로 되어있지 않아서 힘들었네요.

계정이 돌아왔으니까 이슈는 닫겠습니다.

**Comment by outsideris** [comment]
제가 문의 보냈을때는 대답 없었는데! ㅎㅎㅎ 드뎌 돌아와서 반갑네요.
