### ISSUE TITLE
Add weekly updates for 2015-08-21

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#106]
https://github.com/nodejs/evangelism/pull/140/files

**Comment by outsideris** [comment]
원문링크입니다. 
https://medium.com/node-js-javascript/io-js-and-node-js-news-of-august-21st-6c8c49ff5cda

**Comment by marocchino** [comment]
억..깜박하고있었네요 =ㄱ=);;

**Comment by outsideris** [comment]
^^
