### ISSUE TITLE
Add weekly updates for 2015-08-28

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#107]
https://github.com/nodejs/evangelism/pull/142/files

**Comment by outsideris** [comment]
원문 링크입니다. 
https://medium.com/node-js-javascript/io-js-and-node-js-week-of-august-28th-129b6b2f1be6

**Comment by JungMinu** [comment]
@nodejs/iojs-ko 리뷰 부탁드립니다.
https://github.com/nodejs/iojs-ko/pull/110

**Comment by yous** [comment]
Closed via #128.
