### ISSUE TITLE
번역 대상

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#11]
mikeal 에게 문의한 결과, 도움이 되는 문서라면 무엇이든 번역할 수 있다는 답변을 받았습니다( #1 참고 ).

그래서 처음 얘기했던 io.js week 외에도 대상을 확대할 수 있을 것 같습니다.

조금 범위를 작게 가져간다면 트위터의 [@official_iojs](https://twitter.com/official_iojs)가 트윗하는 글 중에 골라서 번역해도 될 것 같고, 원한다면 @outsideris 님이 처음 생각했다는대로 API 문서의 번역을 시도해봐도 될 것 같습니다.

물론 정해지는 번역 대상에 맞춰 폴더 구조라거나 번역 진행 방식 등도 달라져야 할 것입니다.

많은 의견 부탁드립니다.
(제 의견은 댓글로 남기겠습니다)

**Comment by taggon** [comment]
현재 io.js week 만으로는 분량이 너무 작은 듯 하여 일단 공식 트윗에 올라오는 글 중 괜찮아 보이는 것에 대해 번역을 진행해봤으면 합니다. API 문서는 분량도 많고 형식도 따로 맞춰야 할 것 같아서 한국어 번역자 풀이 커진 다음에 시도해보는 것이 좋겠다고 생각합니다.

앞서 말한 두 종류 외에는 번역할만한 컨텐츠를 따로 생각해 둔 것이 없습니다.

**Comment by outsideris** [comment]
저도 weekly만으로는 많지 않아서 추가 번역을 하는 부분에 동의합니다.
API 문서는 node 쪽에 해놓은 게 있긴 하지만 양이 많아서 쉽게 손대기는 어려울것 같습니다.

이 이슈보고 확인해 보니 [웹사이트에 이미 i18n](https://github.com/iojs/website/tree/master/public/kr)이 적용되어 있어서 이부분도 괜찮을것 같습니다.(사이트 자체에는 언어를 바꾸거나 하는 기능이 없어서 번역해서 올리면 적용할 계획이 있는지 마이클한테 확인이 필요하긴 합니다.)

**Comment by taggon** [comment]
**웹 사이트 번역**은 이미 공개되어 있으니 원할 때 작업해도 될 것 같습니다.
우선 번역 대상은 **Medium의 iojs 계정이 발행하는 글**과 **트위터 official_iojs가 트윗하는 글 중 유용하다 싶은 것**으로 정해두면 될 듯 합니다. 더 추가하고 싶은 대상이 있으면 이슈 열어서 의견주세요.
