### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs-ko#1106]
We are going through all of the node.js repositories to rename the primary branch to main. Please see https://github.com/nodejs/node/issues/33864 for more context.

This will require updating: https://github.com/nodejs/nodejs-ko/blob/master/.github/workflows/push.yml.

Is there somebody who can help with that change/in co-ordination with the rename?

**Comment by marocchino** [comment]
I will.

**Comment by marocchino** [comment]
@nodejs/nodejs-ko master브랜치가 main 브랜치로 변경되었습니다.  
```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by mhdawson** [comment]
@marocchino thanks!
