### ISSUE TITLE
About Node.js

### ISSUE THREAD

**Issue by JungMinu** [nodejs/nodejs-ko#113]
https://nodejs.org/en/about/

**Comment by outsideris** [comment]
이부분은 https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/about/index.md 에서 관리되고 있습니다.
해당 부분만 번역하더라도 따로 포스팅할 위치가 좀 애매해서 저는 공식 사이트에서 한글화 페이지가 제공되는게 가장 좋은 현태 같은데 폴더 구조는 i18n이 되어 있지만 아직 사이트는 i18n 준비가 안되어 있는것 같습니다.
node 커미터쪽과 접촉해서 공식 사이트쪽으로 PR을 보내는 쪽으로 해결가능할 지 얘기해 보는게 좋을 것 같은데 어떻게 생각하시나요?
다른 분들 의견도 궁금합니다.

**Comment by yous** [comment]
일단은 `locale/` 디렉터리 아래에 다른 언어로도 제공할 수 있게 만든 것 같으나, 아직 `en`밖에 없네요. https://github.com/nodejs/new.nodejs.org#layout

**Comment by outsideris** [comment]
네 폴더구조는 i18n 생각해서 만든것 같은데 실제로 i18n 서비스하는 코드를 아직 못찾았습니다. 소스를 좀 봐야할것 같아요. i18n 부분까지 지원하게 수정해서 제공하면 마다하진 않을 것 같은데요.

**Comment by JungMinu** [comment]
@outsideris 좋은 의견입니다~ 찬성합니다
+1

**Comment by JungMinu** [comment]
@outsideris 제가 한번 issue로 등록해보겠습니다~

**Comment by JungMinu** [comment]
@outsideris https://github.com/nodejs/new.nodejs.org/issues/123

**Comment by outsideris** [comment]
빠르시군요... 근데 저희랑(?) 얘기하라고 답변 달렸네요. 
제 추측이긴 하지만 이번엔 i18n도 고려해서 구조는 잡았지만 아직 준비는 안된걸로 보입니다. 한꺼번에 많은게 진행중이다 보니 그렇부분이 많더라구요. 주말정도에 시간내서 i18n 코드 좀 봐야겠네요.

참고로 https://github.com/nodejs/Intl 워킹그룹도 있습니다.

**Comment by JungMinu** [comment]
@outsideris 좋은 정보 고맙습니다!
저도 한번 코드 보겠습니다~
