### ISSUE TITLE
Jekyll 설정

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#12]
github page로 배포할 Jekyll 설정.

**Comment by outsideris** [comment]
http://hyde.getpoole.com/ 이 스킨으로 테스트 해볼까 하는데 의견 주세요.
아니면 다른 스킨 좋은거 있으면 추천부탁드립니다.

**Comment by nundefined** [comment]
:+1:

**Comment by taggon** [comment]
깔끔하고 좋네요. :+1:

**Comment by yous** [comment]
https://github.com/iojs/iojs-kr/blob/master/articles/2015-01-27-state-of-io-js.md

> 우리는 워킹 그룹이 앞으로 **전파, 문서화, 지역화, nan[^1](https://github.com/rvagg/nan), 로드맵**을 형성하길 기대합니다.

GitHub에선 마크다운의 `[^1]` 부분이 주석으로 인식되지 않는데, Jekyll 설정 시 Redcarpet 등의 경우 [마크다운 옵션](http://jekyllrb.com/docs/configuration/#markdown-options)에서 footnotes 기능을 켜는 것이 좋을 것 같습니다.

**Comment by outsideris** [comment]
네 Redcarpet 설정 확인했습니다.

**Comment by outsideris** [comment]
http://outsideris.github.io/iojs-kr/ 에 만들어놨습니다.
기존 글은 확인을 위해서 임시로 추가를 해놓은 상태고 지금 PR에 올려져 있는 글 추가되고 jekyll 적용에 다른 이슈가 없으면 제가 합쳐서 다시 올리겠습니다.(어느정도 완료되면 PR로 여기에 합칠 예정입니다.)

## known issues
- io.js라고 쓰기는 그래서 io.js 한국이라고 적었는데 어색한 느낌입니다. 추천 좀...
- 왼쪽에 적어놓은 간단한 소개말 추천해주세요.
- About에 들어갈 내용이 필요합니다.(없으면 제거해도 되고 나중에는 Contibution 가이드등이 추가되면 메뉴로 추가하는 것도 가능합니다.)
- https://github.com/poole/hyde 보시면 색상 선택이나 사이드바를 우측으로 옮길 수도 있는데 의견주세요.

그외 편하게 의견 주세요.
(익스텐션은 tables랑 fanced code block이랑 footnotes를 켰습니다.)

**Comment by hibiyasleep** [comment]
1) 한국어 io.js 정도로 괜찮지 않을까요?

개인적으로 제목에 영어 폰트와 한국어 폰트가 안 어울려 보이는데, 이 부분 폰트를 바꾸면 좋을 것 같습니다.

**Comment by outsideris** [comment]
제목이 왼쪽 사이드바에 있는 제목 말씀하시는거죠?

**Comment by hibiyasleep** [comment]
네. 가독성 좋은 명조 계열이나 그냥 sans-serif 해주셔도 될 것 같습니다

**Comment by marocchino** [comment]
- 위클리와 아티클의 구별을 위해 [태그](https://github.com/pattex/jekyll-tagging)를 사용하는것은 어떨까요? 
- 몇몇 공통으로 쓰이는 정보 이를테면 author, subtitle 등등은 포멧의 일부였으면 좋겠습니다.
- github project의 링크가 잘못되어 있습니다.

**Comment by yous** [comment]
> io.js 관련 소식, 정보, 아티클 등을 한국어로 번역해서 공유합니다.

아티클은 그냥 글이라고 바꿔 적어도 괜찮을 것 같습니다.

**Comment by taggon** [comment]
> io.js라고 쓰기는 그래서 io.js 한국이라고 적었는데 어색한 느낌입니다. 추천 좀...

**io.js 한국팀**이나 **io.js 한국어팀** 정도도 괜찮을 것 같습니다.
어차피 지역 커뮤니티의 중심 역할을 해줬으면 하는 것 같으니 한국팀도 크게 틀린 표현은 아니라 생각합니다.

**Comment by wodory** [comment]
io.js 한글화팀은 너무 문서위주의 표현이겠죠?

**Comment by outsideris** [comment]
위에 나온 내용을 어느정도 추가했습니다. 
http://outsideris.github.io/iojs-kr/
- 태그로 할까 하다가 폴더로 카테고리 구분을 할 수 있어서 폴더로 나누었습니다. 파일관리가 이게 쉬울것 같아서요.
- 원문과 역자를 추가하는 영역을 추가했습니다.

소개는 여전히 없습니다. 메뉴를 뺄까요?

**Comment by taggon** [comment]
소개글은 간단하게 작성해서 넣어도 될 것 같습니다.

**Comment by outsideris** [comment]
다른 이상없으면 현재 PR에 올라온 글 머지되면 jekyll도 머지하도록 하겠습니다.
글의 파일명이나 위치등을 바꿔야 하는 부분이 있어서요.

**Comment by marocchino** [comment]
전부 머지했습니다.
