### ISSUE TITLE
Node.js News — September 4th

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#121]
https://medium.com/node-js-javascript/node-js-news-september-4th-76537eb16d

**Comment by outsideris** [comment]
https://github.com/nodejs/evangelism/pull/146/files

**Comment by marocchino** [comment]
으엉 아직 미디엄에 올리시네요 -ㅅ-;

**Comment by outsideris** [comment]
아~ 저도 습관이 돼서.. ㅎㅎㅎ 
@marocchino https://nodejs.org/en/blog/weekly-updates/weekly-update.2015-09-04/ 에도 같이 올라오더라구요.

**Comment by marocchino** [comment]
앞으로는 https://nodejs.org/en/blog/weekly-updates/weekly-update.2015-09-04/ 에 붙이죠 ㅎㅎ

**Comment by yous** [comment]
위클리 업데이트도 [nodejs/new.nodejs.org](https://github.com/nodejs/new.nodejs.org) 저장소로 옮기는 것 같습니다. https://github.com/nodejs/evangelism/pull/131

**Comment by freenice12** [comment]
요즘 개인적으로 매우 힘들지만, 쌓여있는 이슈가 안타까워 뭐라도 해야겠네요^^;

**Comment by freenice12** [comment]
헤더를

```
---
layout: post
title: Node.js 주간 뉴스 2015년 9월 4일
author: node.js
ref: Node.js News — September 4th
refurl: https://nodejs.org/en/blog/weekly-updates/weekly-update.2015-09-04/
translator:
- <a href="https://github.com/freenice12" target="_blank">freenice12</a>
---
```

이렇게 잡으려고 하는데 잣못된 부분을 말씀해주시면 감사하겠습니다!

**Comment by marocchino** [comment]
잣못 -> 잘못 ... 은 농담이고, 문제 없어 보입니다. :+1:

**Comment by yous** [comment]
Closed via #129.
