### ISSUE TITLE
Technical Steering Committee의 번역 용어 논의

### ISSUE THREAD

**Issue by yous** [nodejs/nodejs-ko#132]
> The Node.js project is now operated by a team of 44 collaborators, 15 of which form its Technical Steering Committee (TSC).

일단 제가 제시한 내용입니다. https://github.com/nodejs/iojs-ko/pull/127#discussion_r39926349

> 'Technical Steering Committee' 번역을 논의해서 정해야 할 것 같은데요, '기술 결정권자' 등은 어떨까 싶습니다. https://en.wikipedia.org/wiki/Steering_committee

**Comment by marocchino** [comment]
'기술 결정 위원회'도 괜찮을 것 같습니다.
위키의 한국어 탭을 누르니 '위원회'로 넘어가네요.

**Comment by yous** [comment]
'기술 결정 위원회' 저도 좋습니다.

**Comment by freenice12** [comment]
+1 입니다.

**Comment by JungMinu** [comment]
+1

**Comment by outsideris** [comment]
:+1:

**Comment by taggon** [comment]
:+1:
