### ISSUE TITLE
Proposal: rename the nodejs/iojs-ko WG to nodejs/nodejs-ko

### ISSUE THREAD

**Issue by srl295** [nodejs/nodejs-ko#148]
Dear members of the io.js Korean WG `iojs-ko`

It is proposed to rename this repo to:

   [nodejs/nodejs-ko](https://github.com/nodejs/nodejs-ko/)

As part of the io.js and node.js convergence, node.js releases are now based on the codebase and user base of the converged node.js and io.js communities. A number of the resources and repositories have already been renamed.
In the absence of objections or other discussion, this rename will occur on or after [Oct 28, 2015](http://time.is/1200AM_28_Oct_2015_in_GMT?iojs-rename)

However, active language working groups should take ownership of this issue and discuss/dispose of it according to their own processes.

For more information or to discuss the overall issue, please see and comment on https://github.com/nodejs/node/issues/2525

This statement was authorized by the Node.js TSC

Cc: @nodejs/iojs-ko

**Comment by outsideris** [comment]
@srl295 
We got it. We will prepare rename our repository.
We should check the link can be broken before renaming it.

**Comment by srl295** [comment]
@outsideris GitHub will redirect it.  Try for example your siblings that were just renamed:
- https://github.com/nodejs/iojs-ka
- https://github.com/nodejs/iojs-ka.git

**Comment by outsideris** [comment]
@srl295 Thank you. We know it, but we want to change it clearly, and we still have some text mentioned as iojs.

**Comment by outsideris** [comment]
- [x] check and fix `iojs` or `iojs-ko` to `nodejs` or `nodejs-ko` in our docuemnts
- [x] change the repository name to `nodejs-ko`
- [x] change twitter account to `nodejs-ko`
- [x] notice renamed repository on twitter

Add check item if I miss something @nodejs/iojs-ko

**Comment by taggon** [comment]
I just opened a ticket that addresses the related tasks. https://github.com/nodejs/iojs-ko/issues/153
