### ISSUE TITLE
nodejs.org home page: New download labels

### ISSUE THREAD

**Issue by fhemberger** [nodejs/nodejs-ko#168]
I added the new download labels for the home page here, which need translation: https://github.com/nodejs/new.nodejs.org/commit/4b54ff301e45ac2c1d636e821e8322af25715d95

**Comment by JungMinu** [comment]
I'll take care of this

**Comment by JungMinu** [comment]
a PR for this issue.
https://github.com/nodejs/new.nodejs.org/pull/295

**Comment by outsideris** [comment]
Thank you.
