### ISSUE TITLE
What You Should Know about Node.js v5 and More

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#171]
https://nodejs.org/en/blog/community/node-v5/

https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/blog/community/node-v5.md

**Comment by freenice12** [comment]
이번엔 한 번 해보고 싶습니다~!... 쪼렙 주제에 시간이 없단 핑계가 절로... ㅎㅎ

**Comment by outsideris** [comment]
closed in #175
