### ISSUE TITLE
공식 명칭에 대한 논의

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#19]
[mikeal이 지역화 팀에 대해 작성한 글](https://medium.com/@mikeal/how-io-js-built-a-146-person-27-language-localization-effort-in-one-day-65e5b1c49a62)을 보면 번역은 물론 지역 커뮤니티에 대해 주도적으로 참여를 이끌어내는 것까지 지역화 팀의 역할로 생각하고 있는 듯 합니다.

따라서 **한국어 번역팀**이라는 명칭은 너무 좁은 의미를 가졌다 생각해서 명칭을 수정했으면 하는데요,
다른 사례를 살펴보면 다음과 같습니다.
1. **한국 커뮤니티** : Mozilla, MongoDB
2. **한국어 지역화팀** : 우분투
3. **현지화팀** : 구글

위 세 가지 중 좋다 생각하는 것이 있으면 말씀해주시고 다른 명칭을 제안해주셔도 좋습니다.

**Comment by taggon** [comment]
저는 1번 한국 커뮤니티를 지지합니다. ^^

**Comment by marocchino** [comment]
저도 1번을 지지합니다. :+1:

**Comment by xarus01** [comment]
1 지지합니다 :+1:

**Comment by nundefined** [comment]
1. 커뮤니티 지지합니다.

**Comment by outsideris** [comment]
이미 대세는 정해진 것 같지만 ^^ 
저는 현재 주활동이 번역에 집중되어 있고 앞으로 커뮤니티의 역할일지는 잘 몰라서 2번을 지지합니다.

**Comment by hibiyasleep** [comment]
1번 지지합니다.

**Comment by taggon** [comment]
과반이 넘어서 공식 명칭은 **io.js 한국 커뮤니티**로 정하겠습니다.
소셜 미디어 및 저장소의 이름도 바꾸어 두었습니다.
