### ISSUE TITLE
Prepare Jekyll 3.0 on Github Pages

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#248]
As [GitHub announcement](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0), 
- GitHub Pages will only support **Kramdown** since May 1st, 2016, but [we're using Redcarpet](https://github.com/nodejs/nodejs-ko/blob/gh-pages/_config.yml#L2). 
- GitHub Pages now only supports Rouge, so we don't need to install Pygments but [we're using Pygments](https://github.com/nodejs/nodejs-ko/blob/gh-pages/_config.yml#L5).

We should change markdown engine and syntax highlight, and check articles whether it showed properly or not.

**Comment by outsideris** [comment]
GitHub notified me about it.

```
The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.
```

**Comment by outsideris** [comment]
지금까지 큰 문제는 없어보이지만 [Gemfile](https://github.com/nodejs/nodejs-ko/blob/gh-pages/Gemfile)에 Jekyll이 2버전대로 지정되어 있어서 GitHub 페이지가 3.x이니 올리는게 좋지 않을까 싶은데요. 그냥 저 파일 고치면 될까요? rubygem은 잘 몰라서요. 

그리고 로컬에서 Jekyll을 실행할 때마다 저만 그런지 `Gemfile.lock`에 변경사항이 생기는데 이건 원래 그런건가요?

```
diff --git a/Gemfile.lock b/Gemfile.lock
index fdac879..13641da 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -64,6 +64,3 @@ PLATFORMS
 DEPENDENCIES
   jekyll (~> 2.0)
   rake (~> 10.0)
-
-BUNDLED WITH
-   1.10.6
```

@marocchino 요즘 바빠보이시지만 루비는 잘 몰라서 소환해봅니다.

**Comment by marocchino** [comment]
번들러버전이 낮으신거같네요.
업데이트하면 괜찮으실것같긴한데 그전에 이거 제가 들고 갈까요?
익숙하기도하고..

**Comment by marocchino** [comment]
일단 그냥 업데이트만 해서 돌려 봤습니다. marocchino/nodejs-ko@65327e4
대충 둘러봤을때는 h3 깨지는 거만 고치면 될것 같은데요?

<img width="230" alt="screen shot 2016-03-04 at 07 43 46" src="https://cloud.githubusercontent.com/assets/128431/13512256/dea8389a-e1dc-11e5-8849-60a6db383110.png">

http://marocchino.github.io/nodejs-ko/

**Comment by marocchino** [comment]
`-`랑 ```를 섞어쓰는 패턴도 깨지네요. 
<img width="475" alt="screen shot 2016-03-04 at 07 56 19" src="https://cloud.githubusercontent.com/assets/128431/13512540/a0c9af0c-e1de-11e5-9e3c-21e51a6c90ce.png">

**Comment by outsideris** [comment]
아 저희 Gemfile에서 2.0으로 지정되어 있어서 Github Page에서도 2.0을 계속 쓰게되는가 보군요.(전 자동으로 3.0이 되는 건줄;;;) 저 깨진것도 같이 고쳐야 겠네요.
제 번들러는 버전 올려보겠습니다.

**Comment by outsideris** [comment]
@marocchino 이거 PR 올려주실 건가요? 아니면 3.0 업그레이드용 브랜치를 하나 만들어서 이 저장소에 올려주시면 제가 그 위에 다른 글 테스트해서 깨지는 내용 수정하도록 하겠습니다. PR로 올라오면 제가 그 위에 수정할 수가 없어서요.

**Comment by marocchino** [comment]
주말에 할려고 했는데, 또 못했네요. ;ㅅ;
브랜치 파놓도록 하겠습니다.

**Comment by marocchino** [comment]
파놨습니다. @outsideris 
https://github.com/nodejs/nodejs-ko/tree/update-jekyll

**Comment by outsideris** [comment]
네 감사합니다.
