### ISSUE TITLE
February 2016 Security Release Summary

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#255]
https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/

https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/vulnerability/february-2016-security-releases.md

**Comment by napiera** [comment]
번역 신청 합니다 ~

**Comment by taggon** [comment]
@napiera 할당해드렸습니다. 잘 부탁드립니다. (__)
