### ISSUE TITLE
iojs-kr에서 iojs-ko으로 변경

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#26]
일단 리스트업만 해보았습니다.
- [x] 공식 웹사이트
- [x] 팀 이름
- [x] 저장소 이름
  - [x] 지킬 수정
- [x] 트위터
- [ ] 미디움
- [x] 트위터에 공지
- ~~팀이름은 잘못 설정하신 것 같은데 고쳐달라고 요청( iojs/website#216 )해 두었습니다.~~ 수정되었습니다.
- 미디움은 rss문제로 보류중입니다.

**Comment by xarus01** [comment]
트위터 계정명 iojs_ko 로 수정했습니다.
bio를 io.js 한국어 커뮤니티로 수정해야 할까요?

**Comment by marocchino** [comment]
> bio를 io.js 한국어 커뮤니티로 수정해야 할까요?

@xarus01 네. 해주세요. :+1:

**Comment by xarus01** [comment]
@marocchino 수정했습니다!

**Comment by outsideris** [comment]
http://iojs.github.io/iojs-ko 여기는 왜 동작 안할까요.. 캐시일까요 ㅠ

**Comment by marocchino** [comment]
Github pages가 커밋을 훅으로 디플로이해서 그럴꺼에요.
#27 머지하시면 나올것 같아요 -0-

**Comment by marocchino** [comment]
개인 추가하는건 [여기](https://github.com/iojs/iojs-ko/settings/collaboration)서 할 수 있습니다.

**Comment by yous** [comment]
@xarus01 트위터 계정 URL로 http://iojs.github.io/iojs-ko/를 설정해 두는 것도 좋을 것 같습니다.

**Comment by marocchino** [comment]
@yous 아마 숫자 영문 언더바만 [허용](https://support.twitter.com/articles/101299-why-can-t-i-register-certain-usernames)될꺼에요.

> A username can only contain alphanumeric characters (letters A-Z, numbers 0-9) with the exception of underscores, as noted above. Check to make sure your desired username doesn't contain any symbols, dashes, or spaces.

**Comment by yous** [comment]
@marocchino 아, 계정마다 위치 정보와 URL을 설정할 수 있습니다. [@official_iojs](https://twitter.com/official_iojs)의 경우엔 https://iojs.org/로 설정되어 있는데, 이 부분을 말씀드린 것이었습니다. :wink:

**Comment by marocchino** [comment]
아! 아이디 이야기인줄알았네요. :sleepy:

**Comment by marocchino** [comment]
미디엄에 관한 논의는 gitter에서 진행중이고 kr->ko로 바뀔 가능성이 없어보이므로 일단 이 이슈는 닫아두겠습니다.
