### ISSUE TITLE
twitter 자동 공지 오류

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#268]
@taggon 2월초부터 트위터로 공지가 안되고 있습니다.
시기상으로 보면 Jekyll이 3.x로 올라간 시기랑 비슷해 보여서 업그레이드되면서 데이터형식이 달라진게 아닐까 합니다.

**Comment by taggon** [comment]
확인해보겠습니다. (__)

**Comment by outsideris** [comment]
공용시스템이 아니다 보니 매번 확인을 부탁드리게 되네요.  (__)

**Comment by taggon** [comment]
수정됐습니다. 업데이트된 소스는 https://github.com/taggon/node_tweet_bot 에서 볼 수 있습니다.
문제의 원인은 알 수 없는 이유로 프로세스가 정상적으로 종료되지 않고 좀비가 되버리는 건데요, 재현이 힘든 버그라 일단은 10분 넘게 지속된 프로세스는 자동 종료되도록 해두었습니다.
