### ISSUE TITLE
AppDynamics, New Relic, Opbeat and Sphinx Join the Node.js Foundation as Silver Members

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#292]
https://nodejs.org/en/blog/announcements/appdynamics-newrelic-opbeat-sphinx/
https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/announcements/appdynamics-newrelic-opbeat-sphinx.md

**Comment by babyso** [comment]
How are you i will like us to know
each other please contact me back with
my ID sophielarry2@hotmail.com
