### ISSUE TITLE
팀 운영 방안 및 번역 가이드라인 논의

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#3]
논의해야 할 사항은 다음과 같습니다. 생각나는 대로 간단하게 쓰느라 말이 다소 짧은 점 이해부탁드립니다.
# 소셜 미디어
1. 트위터 계정([@iojs_kr](https://twitter.com/iojs_kr)은 일단 제 개인 메일을 사용해 만들었습니다.
   1. [x] 그대로 둔다. - 어차피 외부에 노출될 일이 없으므로.
   2. 새 메일 계정을 만든다. - 그래도 공식 계정인데.
2. 트위터 계정과 패스워드는
   1. 모두가 공유한다. - 다 같은 팀원이니까
   2. 책임자 몇 명만 공유한다. - 사람이 많아지면 문제가 생길 확률이 높아지므로
3. 그 외 소셜 미디어 계정을 만든다면 어디에?
   1. [x] Medium
4. 그 외 계정에 대한 관리는(2에서 2를 고른 경우)?
   1. 각 서비스별 담당자를 둔다.
   2. 소셜 미디어 담당자가 한꺼번에 관리한다.
# 번역

FYI, [번역 가이드라인 페이지](https://github.com/iojs/iojs-kr/wiki/Translation-Guidelines)는 만들어두었지만 아직 내용은 비어있는 상태입니다.
1. 이슈 트래커에 등록할 양식  
   (제안) 새 글이 올라오면 translation 레이블을 붙여서 이슈 트래커에 등록한다(글 제목은 이슈 제목으로, 링크는 본문에) → 번역할 사람이 스스로에게 할당하고 진행한다.
2. 번역 리뷰는? 
   1. 필요하다.
   2. 필요하지 않다. - 알아서 잘 하겠지.  
      (제안) 개인적 추천은 1번. TED 동영상 번역 품질이 일정 수준 이상 되는 건 리뷰 덕분이라고 보기 때문. 별도 브랜치에서 글 번역 후 리뷰어에게 공유 → 해당 이슈에 "in review" 레이블 붙여서 리뷰어가 진행 → master 브랜치에 최종 커밋
3. 번역자(와 리뷰어) 크레딧은?
   1. 글 처음에 추가한다. - 눈에 잘 띄는 자리에.
   2. 글 끝에 추가한다. - 잘 안 보이는 곳이라도 있기만 하면 되지.
   3. 필요하지 않다. - 오픈소스 프로젝트에 보상은 없어도 된다.  
      (제안) 2번.
4. 마감 시한은? (할당받은 후 해당 시간 안에 완료하지 못하면 다른 사람에게 할당할 수 있는 시간)
   1. 필요하지 않다.
   2. 1주
   3. 2주 이상  
      (제안) 2번. 빠르게 변하는 오픈소스 프로젝트인만큼 번역도 빨리 이루어져야 한다는 생각. 특히 마감시한이 다른 사람에게 할당하기 위한 것이라고 본다면 1주씩 두 번만 미뤄져도 벌써 3주가 지나게 됨.
# 운영
1. 폴더와 파일 구성은 어떻게?
2. 그 밖에 의사 결정이 필요한 사안이 있을 때 연락 수단은 어떻게?
3. 새로운 참여자는 어떻게 받아들이나?
4. 기존 참여자 중 활동이 저조한 사람에 대한 처우는 어떻게?

---

일단 제가 생각한 것은 여기까지 입니다. 다른 논의 사항이 있다면 추가해주세요.

**Comment by outsideris** [comment]
안녕하세요.

### 소셜 미디어
1. 1 - 새로운 이메일 만들어도 관리될 것 같지 않아서 나중에 인계하면 되니까 개인 메일도 괜찮을듯 합니다.
2. 2 - 일부만 공유에 찬동하지만 아직 초반이라 누가 그 일부일지는 모르겠네요 
3. 다른 소셜은 없어도 되지 않을까요?

### 번역
1. 저도 번역할 부분을 이슈로 등록하고 번역작업을 하는 사람이 할당해서 하면 될것 같습니다. 
2. 리뷰는 하면 좋다고는 생각하지만 그정도 까지 여력이 될지 고민되긴 하네요. 리뷰어가 누가 하냐? 아니면 리뷰어가 번역을 더 잘하냐의 문제가 있고요.
3. 저는 3번이요. 저장소가 있으니 괜찮다고 생각하고 굳이 있어야 한다면 2번이라고 생각합니다.
4. 1 - 마감시한까지는 없어도 될거 ㅅ같습니다.

급 올라온 이슈에 손들었다가 빠른 속도로 진행되고 있어서 아직 감이 안오는데 번역 대상이 무엇인지가 궁금합니다.
이건 마이클의 생각도 궁금하긴 하네요. 웹사이트의 이슈로 올라왔기에 처음에는 웹사이트의 공식 한글화와 API 문서와 관련된 것이라고 생각했는데 올리신 내용 보니까 io.js에 관련된 글에 대한 내용인가 싶기도 해서요.
(일단 io.js 사이트에서 i18n에 대한 인프라가 있는것 같지도 않고요.)
다른 분들은 어떻게 생각하시는지...

**Comment by taggon** [comment]
드디어 첫 의견이네요. 반갑습니다!

일단 번역 대상은 https://medium.com/@iojs 에 있는 글이라고 합니다. 아마도 빠른 속도로 확산하기 위함이 아닐까 하는데요, 역할이 더 확대되게 될지는 모르겠습니다.

번역이라는 게 영어를 한국어로 옮기는 작업인데, 번역자의 역할이 의미를 옮겨오는 것이라면 리뷰어의 역할은 더 자연스러운 우리말로 만드는 것에 있습니다. 출판사의 편집자나 교정자가 역자 분들보다 번역을 잘하거나 전문 지식이 많아서 리뷰를 보는건 아니지만 사실 이분들의 역할은 책의 품질을 담보하는데 중요합니다. 이미 TED 번역에서 경험해봤는데 개인적으로는 장점이 많은 시스템이라 생각합니다.

계정 공유 대상은 서로 잘 협의하여(...;;) 선택해야죠. ^^;

**Comment by outsideris** [comment]
아! #1 에 써있었군요. 
Medium의 글이 대상이라면 [Medium의 번역 프로그램](https://medium.com/the-story/translate-medium-359ebb19d738)을 사용하는 것은 어떨까요? 
Medium의 번역글을 쓸 경우 원본 포맷을 그대로 지킨 상태로 번역을 할 수 있고 완료후에 Medium에서 승인해주고 나면 원본글을 갔을때 사용자자의 언어로 번역이 있으면 상단에 알림을 준다고 합니다.(예시를 못찾겠네요.) 

Medium을 사용했을 때의 장점은 원글과 연결이 되서 국내 사용자가 원글에 방문했을 때도 번역글로 유도를 할 수 있다는 점이고 개인취향일 수도 있지만 Github에 올린것 보다는 보기가 더 편하다고 생각합니다. 검색했을 때 관련 글을 찾는 것도 Medium이 좀더 유리하지 않을까 싶고요.

단점은 각 참여자가 Medium에 번역자로 신청을 해야하는 번거로움이 생기고 Medium에 승인을 받아야 하는 부분도 있습니다. 관리상 이슈할당이나 완료후 리스트업은 이 저장소에 해야하는데 이부분도 상황에 따라서는 불편함이 될 수도 있다고 생각합니다.

**Comment by outsideris** [comment]
리뷰어는 리뷰를 했을 때의 장점에 대해서는 아무런 이의가 없습니다. 번역은 본인이라도 리뷰를 하면 할수록 질이 올라간다고 생각하고 있어서요... 다만 우려를 표했던건 지금 너무 초기라서 개발 프로젝트처럼 Owner나 Maintainer가 없이 신청만 하면 프로젝트에 참여하게 되는 구조인데 누가 리뷰를 하고 이제 등록해도 되겠다고 승인할 수 있는가에 대한 부분이었습니다.

몇명 이상이 OK하면 넘긴다거나 하는 등의 규칙등이 필요할것 같은데 TED에서는 어떤 식으로 했었나요?

**Comment by taggon** [comment]
일단 저희 역할이 Medium 글에 국한되는 건지 정해지지 않은 상태라고 생각하는데다가 번역자와 번역글의 승인을 이 프로젝트와 상관없는 Medium에서 승인받아야 하는 형태는 이상해 보입니다. 리뷰에 대해서도 단순히 노트를 남기는 정도만 가능한 것 같고요. 번역자 참여에 있어 장벽이 된다는 것도 주요한 단점 중 하나입니다.

번역은 GitHub에서 하고 필요하다면 Medium에 공용 계정을 통해 퍼블리싱하는 형태가 가장 좋지 않을까요?

TED 번역은 단순화해서 말하자면 **한 명이 하는 것보다는 두 명이 번역과 리뷰를 보는게 낫겠다**는 식입니다. 번역자가 먼저 번역하고 리뷰어가 다시 손 본 후에는 그대로 퍼블리싱됩니다.

**Comment by xarus01** [comment]
안녕하세요. 반갑습니다.

### 소셜 미디어
1. 현재로써는 어느쪽이든 큰 관계는 없을 것 같네요.
2. 기본적으로 오픈해두는것이 좋을 것 같습니다. 책임자는 있겠지만 공유되어 있는 편이 더 운영에 용이하리라 생각됩니다.
3. 현재는 한꺼번에 관리하는게 더 합리적일것같습니다. 2번에 동의합니다.

### 번역
1. 필요하다고 생각합니다.
2. merge request 시 팀 내 인원들이 자발적으로 review하면 좋을 것 같네요.(다른 사람이 typo만 잡아줘도 굉장히 유용합니다.)
3. Medium의 글을 번역하는 작업이라면 2번 정도라도 크레딧이 필요할 것 같네요. (Github을 사용하는 경우에는 로그에 다 포함되기 때문에 필요하지 않을 것 같습니다.)
4. 일주일 정도 내에 작업이 이루어져야 한다는 의견에 동의합니다.

Medium의 번역 프로그램을 사용하자는 @outsideris 님의 의견에 동의합니다. 다만 Github에서 작업이 review된 후에 Medium쪽 계정 관리자가 올리는 방향으로 가면 더 좋을 것 같습니다.

**Comment by taggon** [comment]
필요하면 공용 Medium 계정은 트위터 [@iojs_kr](https://twitter.com/iojs_kr) 계정을 사용해서 만들면 될 거 같습니다. 관리도 그 편이 더 편할 것 같고요. :)

**Comment by hibiyasleep** [comment]
잘 부탁드립니다.

### 소셜 미디어
1. 1; 비밀번호 복구 등의 용도뿐이니 상관은 없다고 생각합니다.
2. 1; 트위터 계정으로 Medium을 사용한다면 필요할 듯 합니다.
3. 0; 아직 다른 미디어 채널로의 확장은 필요하지 않다고 생각합니다. 필요하다면 Facebook 페이지에 Medium 새 글을 포스팅할 수 있겠네요.

### 번역

@xarus01님 의견에 동의합니다만, 나중에 Medium 글 뿐만 아니라 다른 문서들도 번역하기 시작할 때 마감 기한에 대해서 다시 생각해 볼 필요가 있을 것 같습니다.

**Comment by nundefined** [comment]
안녕하세요.

## 소셜 미디어
1. 계정은 지금 상태로 개인 개정이어도 무방하리라 생각합니다. 어느 시점에서는 계정 변경이 필요할 것이라 생각합니다만 지금 시급한 문제는 아니라고 생각합니다.
2. 트위터 계정과 패스워드의 공유는 트위터를 활용할 방법이 정해진 후에 자연스럽게 결정할 수 있지 않을까요?
3. 급하지는 않으나 일반 사용자가 쉽게 접근할 수 있는 곳을 생각한다면 페이스북 정도가 추가되면 좋겠습니다.

## 번역
1. 제안해주신 방법에 동의합니다.
2. 번역 리뷰는 필요하다고 생각합니다만 실행 방법이 관건이네요. 짝을 정하거나 기간에 따라 당번(?)을 두는 방법도 있을 것 같고..
3. 2번 방법에 한 표 던집니다.
4. 마감 시한은 3번 2주 이상에 찬성입니다. (정확히는 2주)

기본적으로는 원본 글이 올라온 매체를 활용하는 쪽으로 정하면 어떨까 하는 생각이에요. 이런 관점에서 Medium에 올라온 글을 번역해서 medium에 올리면 좋겠습니다. 등록/승인과 같은 부분이 다소 불편하긴 하겠지만 공용 계정으로 해결하거나 medium의 번역 시스템을 사용하지 않는 방법도 가능할 듯 하고요.

**Comment by taggon** [comment]
지금까지 나온 내용에 따라 본문을 업데이트했습니다.
- [x] 트위터 계정에 연결된 메일은 우선 그대로 두기로 했습니다.
- [x] Medium에 계정을 하나 더 추가했습니다. @outsideris 님이 제안하신 Medium 번역 프로그램을 사용할 수 있도록 번역자 계정으로 신청해두었습니다. 답이 오는 대로 업데이트 하겠습니다.
- [x] 새로 참여하신 @nundefined 님의 이름(반가워요~ ^^)과 Medium 계정을 README.md 파일에 추가했습니다.

### 리뷰
- 리뷰는 이 프로젝트에 owner로 등록된 분 중 누구라도 자기한테 할당하고 `in review` 레이블로 바꿔놓은 후  진행하시면 좋을 것 같다는 의견입니다.
- ~~외부에서 Pull Request를 받으면 바로 master 브랜치로 반영되버리는데 상관없을까요? 리뷰를 거치기 전에는 다른 브랜치(draft라거나?)에서 진행하다가 리뷰 완료 후 리뷰어가 master로 병합하는 방법은 어떨까요?~~ 로컬 브랜치로 받을 수 있네요.

### 마감 시한
- 주신 의견을 보면 글의 성격에 따라 마감 기한을 달리 하는 편이 좋을 것 같다는(혹은 가지지 않거나) 생각이 듭니다. 일단 iojs 공식 계정이 밝힌 바에 의하면 매주 io.js week이라는 글을 발행할 계획인 것 같은데, 매주 갱신되는 컨텐츠이니만큼 마감 기한이 1주일로 정해져 있어야하지 않을까요? :)

### 운영
- 다른 건 급하지 않은데 대화 채널이 있으면 좋을 것 같습니다. 이슈트래커는 의견을 나누기에는 그리 적합한 포맷이 아닌 것 같아요. ㅠ_ㅠ

**Comment by nundefined** [comment]
### 리뷰

리뷰도 번역과 마찬가지로 스스로 할당 하고 진행하는 형태네요. 진행 방식으로는 나쁘지 않을 것 같아요. 번역과는 다르게 다수의 리뷰어를 설정하면 어떨까요? 여러 명이 리뷰했을 때의 장점도 있을 것이고 다수의 리뷰어 중 한 분이라도 적당하다고 생각하면 머지할 수도 있을 것 같고요.. 

### 마감시한

글에 따라서 필요한 시간이 다를 것 같다는 생각과 마냥 기다릴 수 없다는 생각을 하다 보니 일주일마다 번역하겠다고 등록한 글에 번역 중이라는 흔적을 남기고 이 흔적이 사전 공지 없이 1주일 이상 끊기면 다른 사람에게 넘길 수 있게 하면 어떨까 하는 생각도 들었습니다. 위에 예시로 나온 1주일마다 새 글이 올라오는 경우에는 적절하지 않을 수도 있겠습니다만..

**Comment by taggon** [comment]
그 사이에 다른 분이 Pull Request 해주신 게 있어서 제가 리뷰 후 머지했는데요( #2 참고 ),
아직 Medium 측에서 답변이 오기 전이라 우선은 트위터에 발행해야 할텐데...
제목과 [GitHub 문서 주소](https://github.com/iojs/iojs-kr/blob/master/weekly/2015-02-06.md)만 넣으면 되는 건지, 담당은 어떻게 정해야 하는 건지, 계정 공유는 누구와 어떻게 해드리면 되는 건지 발행 전에도 정할게 많네요. OTL

**Comment by outsideris** [comment]
저는 Medium에 답변을 기다리고 공유하는것 보다는 홍보차원에서 Github 주소를 공개하고 나중에 Medium으로(이쪽으로 하기로 결정이 된다면요) 공유될때 추가로 올려되 될것 같습니다.

처음이라 여기서 전체 이슈를 정리했는데 약간 얘기가 오갔으니 각 사안별로 이슈를 따로 만드는건 어떨까요?
의견달때 여러가지에 대해서 의견을 한꺼번에 달게 되는것 같아서요.

**Comment by taggon** [comment]
일단 @outsideris 님의 의견을 받아들여서 먼저 GitHub에 있는 문서를 트위터 계정으로 공개했습니다. 논의할 사항은 개별 이슈로 나누어 두겠습니다.

**Comment by taggon** [comment]
다 옮겼습니다. 각 사항에 대해서는 해당하는 이슈에서 논의해주세요.
