### ISSUE TITLE
World’s Fastest Growing Open Source Platform Pushes Out New Release

### ISSUE THREAD

**Issue by napiera** [nodejs/nodejs-ko#325]
https://nodejs.org/en/blog/announcements/v6-release/

https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/announcements/v6-release.md

**Comment by kazikai** [comment]
아직 번역을 다 못했네요. 금일안에 마무리해서 PR 하겠습니다.

**Comment by kazikai** [comment]
PR완료했습니다 리뷰 부탁드립니다.
