### ISSUE TITLE
Enhance contributing guide

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#342]
자주 나오는 리뷰사항에 대한 정리가 필요함  #331 
- `Node v6.0.0 (최신 버전)` -> `Node v6.0.0(최신 버전)` : Node 버전뒤에 괄호 표시는 붙여쓴다.
- `릴리즈` -> `릴리스`
- `https://url` -> `<https://url>` : 링크는 `< >`로 감싸줍니다.
- `##`나 `###`같은 헤딩 전에는 한줄을 띄워야 스타일이 적용됩니다.

```
-->
### Node v6.0.0(최신 버전) 릴리스
```

다음과 같이 바꿉니다.

```
-->

### Node v6.0.0(최신 버전) 릴리스
```

**Comment by outsideris** [comment]
다른 내용 생각나시면 추가해 주세요.

**Comment by yous** [comment]
- `A, B, C 그리고 D` → `A, B, C, D`: `A, B, C, and D` 또는 `A, B, C & D`와 같이 나열하는 문장일 때 `and`, `&`는 번역에서 뺍니다.
- `사물인터넷 (IoT)과` → `사물인터넷(IoT)과`: 괄호 뒤에 조사가 오면 괄호는 앞 단어에 붙여 씁니다. 또한, 조사는 괄호를 제외하고 읽었을 때 자연스럽도록 적습니다.
- ``vm.createContext`과` → ``vm.createContext`와`: 영어 뒤에 조사가 올 때도 읽었을 때 되도록 읽기 자연스러운 방향으로 적습니다.
- Node의 버전 이름은 다음과 같이 번역합니다.
  - `Current`: `최신 버전`
  - `Stable`: `안정 버전`
  - `LTS`: `LTS`
  - `Maintenance`: `유지보수 버전`
- `Core Technical Committee`: `코어 기술 위원회`
