### ISSUE TITLE
nodejs-ko - Korean (조선말)

### ISSUE THREAD

**Issue by GichanLee** [nodejs/nodejs-ko#344]
<img width="527" alt="2016-05-13 10 31 53" src="https://cloud.githubusercontent.com/assets/14211395/15235417/165f7316-18f6-11e6-801b-26b2972faf84.png">
[working-groups](https://nodejs.org/en/about/working-groups/)

이 곳에 제보하는 것이 피드백이 될지는 모르겠지만 nodejs working groups에 Korean이 '조선말'로 되어있네요.
'한국어'라는 표현이 합당해보여서 이렇게 제보드려요.

**Comment by outsideris** [comment]
https://github.com/nodejs/nodejs.org/commit/41fe898c4e6a24dd0620e12519504d4545e7dda9 이 커밋에서 바뀌었군요.왜 바꾼건지 모르겠는데 다시 변경 PR을 보내야겠군요.

**Comment by GichanLee** [comment]
<img width="582" alt="2016-05-13 10 54 04" src="https://cloud.githubusercontent.com/assets/14211395/15235753/0c741052-18f9-11e6-885d-2f011b5f64aa.png">
구글 번역기가 범인이 아닐까 하네요.

**Comment by outsideris** [comment]
@GichanLee 수정되었습니다.
