### ISSUE TITLE
Reconciliation Proposal

### ISSUE THREAD

**Issue by yous** [nodejs/nodejs-ko#37]
번역하는 것이 어떨까요?

https://github.com/iojs/io.js/issues/978

**Comment by outsideris** [comment]
댓글이 너무 많은것 같아서요. 번역보다는 저 제안에 대한 투표를 해야하지 않나 싶은데 본문만 번역해도 의미가 있을까요?

**Comment by marocchino** [comment]
투표 이슈따로, 번역이슈따로하면 될 것 같아요.
