### ISSUE TITLE
투표합시다!

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#38]
#37, iojs/io.js#978

**Comment by marocchino** [comment]
저는 :+1:

**Comment by xarus01** [comment]
좋습니다 :+1:

**Comment by hibiyasleep** [comment]
저도 :+1:

**Comment by outsideris** [comment]
저도 :+1: 
사실 둘이 합친다는데 반대할 사람이 있을까 싶긴 합니다. ㅎㅎㅎㅎ
어떤 형태로 합친다가 궁금하긴 한데 댓글이 너무 기네요. ㅠ

**Comment by taggon** [comment]
다 읽진 못했지만 어차피 제안일 뿐이라 Node.js 쪽에서 안 받아들이면 그만이라는 걱정이 듭니다.
당연히 합친다는데 반대할 이유는 없습니다. ^^;

**Comment by outsideris** [comment]
이 투표가 어떻게 전달되는지도 알아봐야 하긴 하지만... 저희끼리만 투표하는 건 큰 의미는 없어보이는데 어디 SNS같은데 뿌려서 참여하게 해야하지 않을까요?
(근데 그러려면 모르는 사람이 와도 이해할 수 있도록 내용을 좀 정리해야 하긴 하겠네요.)

**Comment by marocchino** [comment]
아 취합해서 리플로 다는 식으로 전달되더라구요.

**Comment by marocchino** [comment]
(참고)
![image](https://cloud.githubusercontent.com/assets/128431/6701725/fbe61c3a-cd63-11e4-8bab-bd60bee5a28a.png)

**Comment by marocchino** [comment]
트위터 어나운스는 한번 있어도 좋을 것 같습니다. 'ㅁ');;

**Comment by outsideris** [comment]
아 그렇네요. 제 계정에서는 한번 했는데 트위터 계정으로도 한번 해야겠네요.
지금 시간에 하긴 그러니 내일 낮에 올릴께요.

**Comment by preco21** [comment]
+1

**Comment by yougjeyou** [comment]
합병 good~~
