### ISSUE TITLE
io.js 주간 뉴스 2015년 3월 20일

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#40]
https://github.com/iojs/evangelism/issues/46

**Comment by outsideris** [comment]
20일자가 왜 안올라오나 하고 있었더니 여기에 올라와있었군요. 댓글보니 마이클한테 미디엄에 올려달라고 얘기해놓은 상태인가 보네요.

**Comment by marocchino** [comment]
원문은 https://github.com/iojs/iojs-ja/pull/63/files 여기를 참고하시면 될 것 같습니다.
