### ISSUE TITLE
migrate to Hexo

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#400]
pros
- JavaScript
- not Ruby

cons
- 작업 필요

requirement
- url은 변경하지말 것. 불가피하게 변경해야 한다면 리다이렉트 필요.
- 필요한 문서 갱신해두기

**Comment by outsideris** [comment]
hexo면 https://hexo.io/ 이거인가요? Jekyll 대신 Hexo로 넘어가는 걸 얘기하시는거죠?

**Comment by marocchino** [comment]
넵.

**Comment by marocchino** [comment]
남은 것
- ~~[ ] twitter 연동 확인~~
- [x] 페이징 관련 문제
- [x] 스테틱페이지 레이아웃
- [x] 디자인
- [x] rake 포팅
- [x] 디플로이 
- [x] 셈플 URL http://marocchino.github.io/nodejs-ko/
- [x] 추가된 기사 리베이스 #401 #402 
- [x] 베이스 브랜치를 master로 변경 https://github.com/nodejs/nodejs-ko/settings/branches
- [ ] 트라비스에서 커밋할 수 있도록 설정 https://travis-ci.org/nodejs/nodejs-ko

**Comment by marocchino** [comment]
제너레이터말고는 얼추된거같은데.. 우리 트위터 발신 스크립트를 어디에 뒀었죠? -0-

**Comment by outsideris** [comment]
@marocchino 글을 트위터로 쏘는 스크립트는 https://github.com/taggon/node_tweet_bot 여기있는데 지금은 안돌아가는 걸로 알고 있습니다. 요즘은 제가 수동으로 올리고 있어요. Lambda로 새로 하나 짜려고 생각중이었는데 Hexo 작업해주시면 거기에 맞춰서 올릴께요.

**Comment by marocchino** [comment]
확인감사합니다.
그럼 그냥 진행해도 되겠네요.

**Comment by taggon** [comment]
@outsideris 직장 옮기고 적응하느라 이래저래 바빠서 못 와봤더니 안 돌아가는지 몰랐네요. 트위터에 잘 올라오길래 잘 되는 줄로만 알았네요. 흐... 수정해둘까요? 아니면 새로 작업하실 건가요? ^^;;

**Comment by marocchino** [comment]
트라비스의 공개 레포 권한만 따로받는 방법이 없나보네요.
일단 수동으로 하겠습니다 ㅜㅜ
이슈는 만들어 둘께요.
nodejs/help#243

**Comment by outsideris** [comment]
@taggon 한창 바빠보이셔서(지금은 왜 바쁘셨는지 알지만요 ㅎ) 확인해달라고 재촉하지 않았습니다. 서버 관리도 피곤한 일이라서 Lambda쪽으로 올려볼까 하고 있는데 어떻게 생각하시나요? 새로운 환경에 적응하시느라 또 바쁘실것 같아서요.

**Comment by outsideris** [comment]
@marocchino 저쪽은 엄청난 토론이 벌어진것 같군요 ㅠ 
Hexo 빌드에 Travis를 쓰는데 private까지 권한이 생겨버려서 올리신 이슈인거죠?

**Comment by taggon** [comment]
@outsideris 제가 그 쪽은 잘 몰라서 얼마나 수고가 들어가는지 잘 모르겠습니다. 크게 수고하지 않으셔도 된다면 찬성입니다. ^^; 그나저나 적응이 필요한 건 마찬가지일 것 같은데, 적응따윈 필요없다 이건가요... ㄷㄷㄷ

**Comment by marocchino** [comment]
@outsideris 네. 그렇습니다. 해결안될 것 같으면 월 $5이하정도에서 설치형으로 운영해도 될거같아요. node랑 git만있으면되는거라..

**Comment by marocchino** [comment]
너무 길어지는 것 같아서, 디플로이 관련 이슈(#413)를  별도 만들었습니다.
