### ISSUE TITLE
Cars.com and Dynatrace join the Foundation to support the stability and success of the Node.js platform

### ISSUE THREAD

**Issue by napiera** [nodejs/nodejs-ko#414]
https://nodejs.org/en/blog/announcements/cars-dynatrace/

https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/announcements/cars-dynatrace.md

**Comment by taggon** [comment]
2주가 지나도록 맡는 분이 없으셔서 제가 맡겠습니다. ^^;

**Comment by outsideris** [comment]
이 작업 확인 부탁드립니다 ^^

**Comment by taggon** [comment]
출장때문에 좀 늦어졌네요. 이번 주 내로 완료하겠습니다.

**Comment by taggon** [comment]
실수로 제 저장소를 리셋하면서 작업 중인 글이 날아가 버렸습니다. ㅠㅠ 아무래도 완성하지 못할 것 같아서 할당했던 걸 해제했습니다. 혹시 다른 분이 하실 거라면 맡아서 하셔도 됩니다.

**Comment by devjin0617** [comment]
제가 진행해보겠습니다.

**Comment by taggon** [comment]
Closed per #515
