### ISSUE TITLE
Node.js Foundation Announces Schedule for Second Annual Node.js Interactive North America

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#422]
https://nodejs.org/en/blog/announcements/interactive-2016-north-america-schedule/

https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/announcements/interactive-2016-north-america-schedule.md

```
npm run scaffold https://raw.githubusercontent.com/nodejs/nodejs.org/master/locale/en/blog/announcements/interactive-2016-north-america-schedule.md
```

**Comment by kazikai** [comment]
이부분 제가 번역하려고 했는데.. 요즘 시간이 여의치 않아 못하게되었네요 ㅠㅠ assignees에서 일단 나오겠습니다. 
오래 들고있어서 죄송하네요ㅠㅠ
