### ISSUE TITLE
Security updates for all active release lines, September 2016

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#426]
https://nodejs.org/en/blog/vulnerability/september-2016-security-releases/

https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/vulnerability/september-2016-security-releases.md

**Comment by lucykang** [comment]
안녕하세요. 지금 파일 생성중인데 에러가 뜨네요. 혹시 제가 쓰고 있는 command 가 잘못된건가요? 

`npm run scaffold https://raw.githubusercontent.com/nodejs/nodejs.org/master/locale/en/blog/vulnerability/september-2016-security-releases.md 2016-09-25`

**Comment by lucykang** [comment]
![image](https://cloud.githubusercontent.com/assets/11581464/18816387/d7dedbbe-8316-11e6-9196-d2e1e11f4ad8.png)

**Comment by outsideris** [comment]
@lucykang 혹시 Node.js 버전이 어떻게 되시나요?

**Comment by outsideris** [comment]
@lucykang Node.js v4.x에서는 오류가 생기네요 6을 쓰고 있어서 몰랐습니다. v4에 맞춰서 수정하도록 하겠습니다. 

`source/_posts/2016-09-25-vulnerability-september-2016-security-releases.md` 경로에 [이 파일의 내용](https://gist.githubusercontent.com/outsideris/a9132de6b96b9c53cede4e4ce195f631/raw/18c2c2528f0a3ecc49a744bc4b907c57eb66035b/2016-09-25-vulnerability-september-2016-security-releases.md)으로 번역작업하시면 수정해놓겠습니다.

**Comment by lucykang** [comment]
@outsideris 네 감사합니다.

**Comment by lucykang** [comment]
오늘 저녁까지 최대한 끝내겠습니다. 늦어져서 죄송합니다.
