### ISSUE TITLE
scaffold script throw an error in v4.x

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#427]
see #426

**Comment by marocchino** [comment]
에러 메세지만 보면 디스트럭쳐링을 지원안하나보네요.
ref: http://kangax.github.io/compat-table/es6/#node4

**Comment by outsideris** [comment]
제가 수정해보겠습니다. v4를 쓰는 사람도 많아서 4로 수정해야 할 것 같습니다.

**Comment by marocchino** [comment]
이렇게 변경 많이 할 줄 알았으면 좀 테스트라도 짜둘걸 그랬네요.
죄송합니다. 부탁드리겠습니다.

**Comment by taggon** [comment]
어차피 v7도 나올 마당에 그냥 기준 환경이 v6라고 안내하면 되지 않을까요? 저희 저장소가 소프트웨어 서비스를 제공하는 곳도 아닌데 굳이 내년 4월쯤 개발이 중단되는 v4까지 지원할 필요는 없다 생각합니다. 게다가 v6도 10월부터는 장기 지원(LTS)이 되어 v4를 서서히 대체하게 될테고요.

**Comment by outsideris** [comment]
큰 노력이 드는거 아니면 v4 지원으로 수정해도 되지 않을까요? 번역하시는 분들이 Node.js에 대해서 다 잘 아시는건 아닌것 같아서요. 그리고 v4는 2018년 4월까지는 유지보수 될꺼긴 한대 v6 LTS로 얼무나 빨리 교체가 이뤄질 지 잘 모르겠네요.

**Comment by outsideris** [comment]
라고 썼지만 살짝 수정해봤더니 디스트럭쳐링만 바꾼다고 되진 않네요 ㅋㅋ
