### ISSUE TITLE
한국어 다운로드 페이지

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#436]
영문은 current, current version으로 구별이 되있는데 우리는 둘 다 최신버전으로 되어있어,
LTS의 최신버전을 current의 최신버전으로 오해할 수 있습니다.

구별할 필요가 있어보이는데 어떻게 생각하시나요?

![screen shot 2016-10-03 at 20 26 25](https://cloud.githubusercontent.com/assets/128431/19035944/bc105380-89a7-11e6-807f-7c68370e0dc8.png)

https://nodejs.org/en/download/current/

![screen shot 2016-10-03 at 20 27 58](https://cloud.githubusercontent.com/assets/128431/19035986/104042f8-89a8-11e6-8bb6-10f984411400.png)
https://nodejs.org/ko/download/current/

**Comment by outsideris** [comment]
진짜 그러네요.. 흠.. 이건 번역 용어를 정리하기 전에 영어에서도 current, current version과 애매하게 써있지 않나 싶은데 홈페이지 쪽에 이슈를 먼저 제기해 볼가요? 영어에서는 저 의미가 명확한 걸까요?

**Comment by marocchino** [comment]
제가 영어를 잘 못해서... >,<; 아웃사이더님이 하고 싶으시면 하시는 거죠. 😃

**Comment by outsideris** [comment]
일단 https://github.com/nodejs/nodejs.org/issues/944 에 질문을 올려놓았습니다. ㅎ

**Comment by devjin0617** [comment]
https://nodejs.org/ko/

여기에는 current 가 "현재버전" 으로 표기되어 있네요 😃

**Comment by outsideris** [comment]
아 그러네요. 저기도 최신버전으로 바꾸어야 겠군요.

**Comment by outsideris** [comment]
일단 저희만 헷갈리는 건 아니더군요. 더불어 토글 UI와 함께 js에서 유명한 [2ality를 트위터에서 꼬셔서](https://twitter.com/rauschma/status/785139071903498240) 이슈로 데려와서 좀 붐엄(?)이 된듯합니다. 저쪽 이슈 진행상황을 보고 움직이면 될 것 같습니다.

**Comment by marocchino** [comment]
음.. 정리 됐네요 -3-

**Comment by outsideris** [comment]
네 https://github.com/nodejs/nodejs.org/pull/945 여기서 Latest LTS와 Latest Current로 정리가 되었네요.
우리는 `Current`를 `최신 버전`으로 적고 있었는데 Latest Current는 뭐라고 번역하는게 좋을까요?

**Comment by marocchino** [comment]
대량의 리플레이스가 발생하겠지만, 
최신 LTS 버전
최신 현재 버전
가 제일 무난해보이는데 어떠신가요.

**Comment by outsideris** [comment]
`Current`를 `최신 버전` 대신 `현재 버전`으로 바꾸자는 얘기시죠? 저도 딱히 아이디어는 없는데 `최신 현재 버전`이라는 말이 어색하게 들리지 않을까요? 대량 리플레이스한다음에 트위터 등에 공지등은 한번 하면 될것 같긴 하지만요.

**Comment by devjin0617** [comment]
`Current` -> `현재 버전`이 제일 무난할 것 같기는 한데, `진행 버전`이라고 하면 좀 이상할까요?
그런데 지금 node.js 다운로드 페이지를 보니

```
LTS v4.x : Recommended For Most Users
LTS v6.x : Latest Features
```

이렇게 변경되었네요;;;

**Comment by outsideris** [comment]
네 그건 LTS가 새로 나와서 그렇습니다. 7.0이 조만간 나오면 다시 `Current`가 등장할 겁니다.

**Comment by marocchino** [comment]
> 최신 현재 버전이라는 말이 어색하게 들리지 않을까요? 

아마... "현재 버전: 최신 기능." 식으로만 이야기 될거라 문제 없어 보입니다.

**Comment by outsideris** [comment]
논의가 오래되었으니 그럼 `현재 버전`으로 바꾸시죠. 이 이슈는 수정을 완료하면 닫겠습니다.
