### ISSUE TITLE
번역 Collaborator 신청

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#44]
Collaborator로 참여하고 싶으신 분은 이 이슈에 댓글 달아주시면 추가해 드립니다.

**Comment by asbubam** [comment]
안녕하세요! asbubam입니다. 도움될 수 있는 부분이 있다면 참여하고 싶어요.

**Comment by blueprajna** [comment]
안녕하세요. 블로그 피드에서 보고 왔습니다. 도움이 될수 있는 부분이 있다면 참여하고 싶습니다.

**Comment by harryoh** [comment]
혹시 도움이 될 수 있는게 있으면 좋겠습니다.​

**Comment by marocchino** [comment]
@asbubam 님, @blueprajna 님, @harryoh님 을 Collaborator로 초대 했습니다.

**Comment by wafe** [comment]
안녕하세요! 저도 참여하고 싶습니다.

**Comment by marocchino** [comment]
@wafe 님을 초대 했습니다.

**Comment by freenice12** [comment]
안녕하세요. 
블로그에서 소식을 접하고 왔습니다!
도움이 될 수 있다면 참여하고 싶습니다!

**Comment by marocchino** [comment]
@freenice12님을 초대했습니다.

**Comment by creamer** [comment]
안녕하세요.
능력은 별로 없지만 조금이라도 도움이 될 수 있을까하고 참여 신청 드립니다.

**Comment by outsideris** [comment]
@creamer 추가했습니다.

**Comment by JungMinu** [comment]
안녕하세요!
Collaborator로 참여하고 싶습니다!

**Comment by marocchino** [comment]
@JungMinu 추가했습니다.

**Comment by sungjk** [comment]
안녕하세요. 번역 작업에 참여하고 싶습니다!!

**Comment by marocchino** [comment]
@SungjungKim 추가했습니다.

**Comment by kazikai** [comment]
안녕하세요^^ 저도 번역작업에 참여하고싶습니다. 감사합니다:)

**Comment by outsideris** [comment]
@kazikai 추가했습니다. https://github.com/nodejs/nodejs-ko/blob/gh-pages/CONTRIBUTING.md 를 참고해 주세요.

**Comment by typeon** [comment]
저도 가능하면 돕고 싶습니다.

**Comment by marocchino** [comment]
@typeon 초대했습니다. :smile:

**Comment by napiera** [comment]
안녕하세요, 이제 github 걸음마를 뗴는 신생 개발자 입니다. 저도 번역 작업을 돕고 싶습니다.

**Comment by marocchino** [comment]
추가했습니다.

**Comment by webix** [comment]
안녕하세요, 저도 번역 참여하고 싶습니다.

**Comment by outsideris** [comment]
@webix 추가했습니다.

**Comment by kyungw00k** [comment]
안녕하세요, (번역이 겁나긴 하지만) 도움이 되고 싶습니다!

**Comment by outsideris** [comment]
@kyungw00k 추가했습니다 ㅎㅎㅎ

**Comment by jays1204** [comment]
안녕하세요! 요새 node 체인지 로그에 관심이 많아지다보니 번역본에도 한번 참여하고 싶은데 혹시 참여 가능할까요??

**Comment by marocchino** [comment]
추가했습니다.

**Comment by bexoss** [comment]
저도 참여하고 싶습니다!

**Comment by outsideris** [comment]
@bexoss 추가했습니다.

**Comment by erishforG** [comment]
참여 신청합니다!

**Comment by outsideris** [comment]
@erishforG 추가했습니다.

**Comment by chulkyoo** [comment]
참여 신청하고 싶습니다.

**Comment by marocchino** [comment]
초대했습니다.

**Comment by LangleyJack** [comment]
Node.js을 가지고 프로젝트를 진행하면서 관심이 생겼습니다. 번역작업에 참여하고 싶습니다.

**Comment by outsideris** [comment]
초대했습니다.

**Comment by sohyeonlee** [comment]
안녕하세요 저도 참여 신청하고 싶습니다.

**Comment by outsideris** [comment]
초대했습니다.

**Comment by TanChoi** [comment]
안녕하세요. 번역작업 참여하고 싶습니다.

**Comment by outsideris** [comment]
추가해 드렸습니다.

**Comment by pineoc** [comment]
번역작업에 참여하고 싶습니다!

**Comment by outsideris** [comment]
@pineoc 추가해드렸습니다.

**Comment by michaelleevan** [comment]
안녕하세요. 번역작업 참여를 신청합니다

**Comment by jeehaepark** [comment]
안녕하세요! 번역작업 참여하고싶습니다.

**Comment by marocchino** [comment]
@michaelleevan @jeehaepark 추가해드렸습니다.

**Comment by mingyu-lee** [comment]
번역작업 참여하고 싶습니다

**Comment by KyoungRan** [comment]
안녕하세요. 번역작업 참여신청합니다.

**Comment by marocchino** [comment]
@mingyu-lee @KyoungRan 추가했습니다.

**Comment by devjin0617** [comment]
안녕하세요. 처음진행을 해보는거라 차근차근 진행해보고 있습니다.
번역작업에 참여신청합니다.

**Comment by outsideris** [comment]
@devjin0617 추가했습니다.

**Comment by lucykang** [comment]
안녕하세요. collaborator 로 참여하고 싶습니다.

**Comment by marocchino** [comment]
@lucykang 추가했습니다.

**Comment by hyeongukryu** [comment]
저도 참여하고 싶습니다 👋

**Comment by marocchino** [comment]
@mintrupt 추가했습니다.

**Comment by ibizcox** [comment]
안녕하세요. 저도 번역에 참여하고 싶습니다.

**Comment by 14ypark** [comment]
참여 신청합니다..

**Comment by outsideris** [comment]
추가했습니다.

**Comment by DaleSeo** [comment]
안녕하세요. 번역 참여 신청합니다!

**Comment by outsideris** [comment]
추가했습니다.

**Comment by Hot6ix** [comment]
신청합니다

**Comment by outsideris** [comment]
@Hot6ix 추가했습니다.

**Comment by originerd** [comment]
저도 참여하고 싶습니다 :grin:

**Comment by marocchino** [comment]
@originerd 추가했습니다.

**Comment by DongHyunSong** [comment]
저도 추가해주세요~!

**Comment by marocchino** [comment]
@DongHyunSong 추가했습니다.

**Comment by jeonghwan-kim** [comment]
참여하고 싶습니다 😃

**Comment by MJayJang** [comment]
안녕하세요 Collaborator 신청합니다!

**Comment by outsideris** [comment]
@jeonghwan-kim @MJayJang 두분 추가해드렸습니다.

**Comment by eunsucking** [comment]
참여 신청합니다.

**Comment by outsideris** [comment]
추가해드렸습니다.

**Comment by Seojiwoong** [comment]
안녕하세요 참여하고싶습니다!

**Comment by writingdeveloper** [comment]
안녕하세요~ 번역 참여하고자 신청드려봅니다!

**Comment by marocchino** [comment]
이제 신청안하셔도됩니다. 그냥 열려있는 이슈집어가세요.
