### ISSUE TITLE
[참여 가이드 업데이트] 메인테이너에 교정자로서의 역할 추가

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#456]
Node.js가 빠르게 발전하는 플랫폼이다 보니 리뷰를 하다가 화제가 되는 시기를 놓치는 경우가 왕왕 있습니다. 그렇다고 리뷰를 하지 않을 수는 없는 노릇이고요.

그래서 글의 내용과는 상관없는 "간단한 맞춤법 오류, 서식 오류, 오타 등은 메인테이너가 수정할 수도 있다"는 내용을 번역 참여 가이드에 명시하고 그대로 실천했으면 합니다. 간단한 오류 정도는 조금이라도 빠르게 수정해서 낼 수 있었으면 합니다.  마침 GitHub에 관련 기능이 추가되었기도 하고요. @nodejs/nodejs-ko 다른 분들 의견은 어떠신가요?

**Comment by outsideris** [comment]
전 사실 간단한 문법오류등은 바로 수정해서 내기도 했지만 그런 부분이 필요하다는 것에 동의합니다. 
링크 걸려고 들어갔더니 이미 팀 멤버 정리에도 글을 써 주셨네요. nodejs-ko 팀 멤버들을 기준으로 그런 룰을 추가하는 것에 동의합니다.

**Comment by pineoc** [comment]
글의 맞춤법 오류, 서식 오류, 오타에 대한 부분은 메인테이너가 수정할 수 있다고 생각합니다.
동의합니다.
