### ISSUE TITLE
Weekly Update - December 25th, 2016

### ISSUE THREAD

**Issue by devjin0617** [nodejs/nodejs-ko#487]
https://nodejs.org/en/blog/weekly-updates/weekly-update.2016-12-25/

https://raw.githubusercontent.com/nodejs/nodejs.org/master/locale/en/blog/weekly-updates/weekly-update.2016-12-25.md

**Comment by kazikai** [comment]
금주내에 번역하고 commit 하겠습니다.

**Comment by yous** [comment]
Closed via #497.
