### ISSUE TITLE
Interested in Contributing to Node.js Core? Read On.

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#506]
https://medium.com/@nodejs/interested-in-contributing-to-node-js-core-read-on-5614f60d074d#.da1kujv13

이글은 Medium 글이라 scaffold로는 동작하지 않고 직접 Markdown으로 복사해야 합니다.

**Comment by pineoc** [comment]
일주일전에 받아갔는데 번역할 내용이 많아서 조금 지연됬습니다. 이번주 안에 번역 완료하겠습니다!

**Comment by yous** [comment]
Closed via #539.
