### ISSUE TITLE
Volunteers Needed for the Next Phase of the Node.js Certified Developer Program

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#507]
https://medium.com/@nodejs/volunteers-needed-for-the-next-phase-of-the-node-js-certified-developer-program-eeb631effc49#.tzasgab43

이글은 Medium 글이라 scaffold로는 동작하지 않고 직접 Markdown으로 복사해야 합니다.

**Comment by pineoc** [comment]
제가 자주 미디엄 글을 번역하게 되는 것 같네요 :)
이번글은 저번 것 보다 길지 않아서 다행인 것 같습니다. ㅎㅎ

**Comment by pineoc** [comment]
번역끝나고 머지가 다 되어서 이슈 닫겠습니다.
