### ISSUE TITLE
Why Developers and Enterprises Heart Node.js

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#508]
https://medium.com/@nodejs/why-developers-and-enterprises-heart-node-js-e26afd2f30c8#.2t2d2ht75

이글은 Medium 글이라 scaffold로는 동작하지 않고 직접 Markdown으로 복사해야 합니다.

**Comment by taggon** [comment]
이 글은 번역하려고 봤더니 글 안에 포함된 인터뷰 동영상을 소개하는 글이더라고요. 주요 컨텐츠는 동영상인데, 이건 번역을 할 수가 없고요. =_=;;

**Comment by outsideris** [comment]
앗 죄송;; Medium 공식 계정에 글이 올라왔길래 가져왔는데 말씀하신대로 동영상이 대부분이라 애매하네요. 이 이슈는 닫겠습니다.
