### ISSUE TITLE
assert의 번역 용어 관련 

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#51]
번역할 때 이슈가 되어 따로 용어 정의를 논의하기 위한 내용입니다.

예시: 

> Calling `dns.setServers()` while a DNS query is in progress can cause the process to crash on a failed assertion [#894](https://github.com/iojs/io.js/issues/894)

위 문단에서 `failed assertion`을 `단언문 실패`로 번역할 지(현재 사용 중) 아니면 단언문이 많이 보급되지 않았으므로 `어서트` 혹은 `assert`로 할 지에 대한 의견 부탁드립니다.

**Comment by blueprajna** [comment]
단언문 실패은 좀 어색한 느낌이 드는것 같습니다.
'실패 단언문' 정도는 괜찮은거 같습니다.

**Comment by harryoh** [comment]
번역상으로는 단언문 실패가 맞는 것 같은데 아무래도 의미가 와닿지는 않네요.
앞으로 failed assertion 이라는 단어는 자주 나올테니 일관성만 지키면 큰 문제는 없다고 생각합니다.

그래도 둘중 하나를 고르라면 아무래도 assert 가 낫지 않을까 싶기는 합니다. ^^;;

**Comment by yous** [comment]
참고 사항으로, assertion과 관련하여 처음 진행된 논의는 여기에서 보실 수 있습니다. https://github.com/iojs/iojs-ko/pull/39#discussion-diff-26633914

**Comment by resourceful** [comment]
저도 번역을 중에 비슷한 용어로 고민을 하다 우연히 들어와 보게되었습니다. 이슈가 발생한지 좀 지나서 지나치려고 했지만, failed assertion 은 실패"된" 단언문 이라고 과거형이 나타나도록 써야 맞지 않나 싶어서 글을 남깁니다. 
- 실패된 단언문으로 인해 프로그램이 ...

**Comment by freenice12** [comment]
저도 실패한 단언문 또는 실패된 단언문에 한 표!

**Comment by taggon** [comment]
**실패한 단언문**에 한 표 더 합니다.
굳이 "된"이라는 수동형을 쓸 필요는 없을 것 같습니다.

**Comment by yous** [comment]
저도 '실패한 단언문'이 좋습니다.

**Comment by outsideris** [comment]
저도 실패한 단언문 좋습니다.

**Comment by taggon** [comment]
이 논의는 **실패한 단언문**으로 결정됐다고 보고 닫아도 될 것 같은데, 어떠신가요?

**Comment by marocchino** [comment]
네. 닫아도 될 것 같습니다. \'ㅁ'/
