### ISSUE TITLE
리뷰의 기준 + 시험적인 레이블 추가

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#532]
리뷰의 기준과 시험적인 레이블에 대해서 의견을 나누고 싶습니다. 이 이슈는 관련 내용을 기록으로 남겨두는 편이 좋을 것 같아서, 그리고 나중에 누군가 근거를 궁금해하거나 가이드를 문서화할 때 참조하기 좋으라고 등록합니다.

## 리뷰의 기준
저는 "**2명 이상의 승인이 있으면 바로 머지할 수 있다.**"라는 기준을 정해두었으면 합니다. 전에 비슷한 걸 정했던 것도 같은데 확실하지 않아서 논의를 올려봅니다.

## 시험적인 레이블 ready to merge
그리고 두 번째 승인해주는 리뷰어는 태그에서 **in review**를 제거하고 **ready to merge**를 달아주었으면 합니다. 리뷰는 컬레버레이터들도 가능하고, 머지는 멤버만 가능한 걸로 아는데 누구라도 이 태그를 먼저 본 멤버가 머지해주면 좋을 것 같습니다. 그래서 현재 시험적으로(#531 참고) 이 레이블을 추가해보았습니다. 이상하다 생각하는 분이 많으면 제거하겠습니다.

**Comment by devjin0617** [comment]
감사합니다. 좋은 것 같습니다!
말씀해주신대로 지금까지 계속 2명 이상의 리뷰완료 후 머지되는 것이 기준으로 알고 있습니다. 그런데 2명 리뷰완료 후 3번째, 4번째 리뷰 해주실 때 더 많이 의견교환이 되었던 것을 보게 되었는데, 2명으로 리뷰를 완료/머지하는 것이 맞는 건지 잘 모르겠습니다 T_T


+ 아, 그리고 Collaborator도 머지가 가능한 것 같습니다
<img width="776" alt="merge" src="https://cloud.githubusercontent.com/assets/5671786/23833146/053169cc-0785-11e7-854a-921b9f46ba0d.png">

**Comment by yous** [comment]
네, 대부분의 경우 두 명의 리뷰면 머지하고 있었으니 이 기준으로 가도 문제 없을 것 같습니다.

ready to merge 레이블을 사용하면 리뷰가 이런 식으로 이뤄질 것 같네요.

- 풀 리퀘스트 생성 시 translation, in review 레이블 추가
- 두 번째로 승인한 리뷰어가 in review 레이블 제거, ready to merge 추가
- 머지하는 멤버가 머지 후 ready to merge 제거

**Comment by outsideris** [comment]
상세 룰은 아직 없지만 기본 룰은 https://github.com/nodejs/nodejs-ko/blob/master/CONTRIBUTING.md 에 있고 콜라보레이터도 머지는 가능합니다.

저는 2명 이상 기준이라는 규칙을 명문화하는거 좋은것 같습니다. 이미 그렇게 하고 있고요.. 
2명이상 승인하면 머지할 최소 조건이 된것이니 그 뒤에 추가 논의가 이뤄지는 것은 상황에 따라 조정하면 될것 같습니다. 논의 중에 머지하거나 하진 않을것 같고 2명 승인은 최소조건이라고 생각해서요.

**Comment by marocchino** [comment]
재경우는 제가 두번째인 경우는 그냥 머지했었는데 한번더 확인절차를 두고싶으신건가요?

**Comment by outsideris** [comment]
여태 그렇긴 했는데 암묵적인 룰이므로 명문화하자는 것으로 이해했습니다. 나중에 들어오신 분은 언제 머지해야할지 잘 모르는 부분도 있고요. 대부분은 ready to merge를 달기전에 마지막 사람이 머지를 할 가능성이 높다고는 보지만요.

**Comment by taggon** [comment]
논의 내용을 보다보니 '두 사람이 리뷰 승인하면 머지'라는 규칙을 정해두면 두 번째 사람이 리뷰 승인하고 바로 머지하면 되니까 ready to merge 레이블은 없어도 될 것 같네요.
리뷰 인원만 명문화 해두면 될 것 같습니다. :)

**Comment by marocchino** [comment]
네 좋네요. :)
