### ISSUE TITLE
Thoughts on Node Foundation

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#55]
https://medium.com/@programmer/thoughts-on-node-foundation-abcf86c72786

**Comment by outsideris** [comment]
이런 글은 작성자한테 연락해서 번역 허락 받아야 하지 않을까요?

**Comment by marocchino** [comment]
https://medium.com/@marocchino/thank-you-for-your-article-i-found-it-interesting-and-translated-it-to-share-with-my-friends-in-9559910c4c9a
질문 해두었습니다. 대답오면 다시 리플 달꼐요 'ㅁ'/

**Comment by marocchino** [comment]
대답이 안오니 일단 닫아두었다 오면 다시 열겠습니다. -ㅅ-);

**Comment by outsideris** [comment]
네 ㅠㅠ 저도 하나 문의해 놓은거 있는데 씹혔어요 ㅠ
