### ISSUE TITLE
io.js の v2.0 が出ました。

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#58]
http://yosuke-furukawa.hatenablog.com/entry/2015/05/06/170034

**Comment by marocchino** [comment]
허락 받았습니다. 'ㅅ');
https://twitter.com/yosuke_furukawa/status/595860778235858944

**Comment by outsideris** [comment]
일어 가능하신 분이 하셔야 겠네요 ㅎ(전 까막눈이라...)

**Comment by marocchino** [comment]
제가 하죠.

**Comment by asbubam** [comment]
앗 일어 저도 할 수 있어용.. 다음에 일어는 저에게!! throw 해주세용.

**Comment by marocchino** [comment]
@asbubam 아.. 그러시면 가져가실래요? 전 내일부터시작할 수 있을것 같아서..

**Comment by asbubam** [comment]
@marocchino 네, 제가 해보겠습니다. 감사합니다!

**Comment by asbubam** [comment]
어싸인 받아놓고, 번역이 너무 느리네요. 파이팅 하겠습니다.

**Comment by marocchino** [comment]
:dancers:

**Comment by marocchino** [comment]
@asbubam 님 잘 되가고 계신가요? 'ㅁ'

**Comment by asbubam** [comment]
@marocchino 앗 https://github.com/asbubam/iojs-ko/tree/2015-05-06-io-js-v2.0-released 여기서 진행중인데, 너무 느려서 큰일입니다. 이번 주말에 힘을 내보려고 하고 있습니다. ㅠ_ㅠ;
