### ISSUE TITLE
README.md 관련

### ISSUE THREAD

**Issue by freenice12** [nodejs/nodejs-ko#592]
한국 커뮤니티가 아래 주소로 링크가 되어있고 기본적으로 /en/이 붙는 상황인것 같습니다.
링크를 따로 /ko로 해줘야 할까요?
https://nodejs.org/

**Comment by marocchino** [comment]
어느 페이지에서 그쪽으로 링크되어있나요?

**Comment by freenice12** [comment]
https://raw.githubusercontent.com/nodejs/nodejs-ko/master/README.md

최초 페이지(README.md)에 
```
[Node.js](https://nodejs.org/) 한국 커뮤니티
```
로 링크가 걸려있습니다.

쓰고 보니까 Node.js 는 본진이고 우리가 한국 커뮤니티 입니다. 라고 써논것 같군요... ㅠㅠ
혼란을 드려 죄송합니다.

**Comment by outsideris** [comment]
네.. 이슈 닫겠습니다. ㅎㅎ
