### ISSUE TITLE
Create organization for nodejs-ko members

### ISSUE THREAD

**Issue by eunsucking** [nodejs/nodejs-ko#593]
nodejs-ko member용으로 organization을 만드는건 어떤가요?

1.github mention을 organizaion으로 할 수 있어서 편할거 같아요
(https://github.com/blog/1121-introducing-team-mentions) 

nodejs 관련 사이트, 예를들면 지금 저는 [https://nodeschool.io/](url) 에 있는 workshop들을 몇개 번역해 보려고 하는데, 번역 리뷰 같은거 요청할때, organization으로 맨션하면 편할거 같습니다.

2.뱃지가 갖고싶네요 +_+

뱃지 이미지는 nodejs_ko 트위터계정(https://twitter.com/nodejs_ko) 프로필사진으로 어떤가요?

**Comment by taggon** [comment]
nodejs라는 organization에 소속된 nodejs-ko 팀이라서 따로 organization을 만드는 건 적절하지 않은 것 같습니다. 멘션은 @nodejs/nodejs-ko 로 하실 수 있고요. 뱃지는... @nodejs 뱃지가 더 멋지지 않나요? ^^;

**Comment by eunsucking** [comment]
@taggon 아 멘션가능하군요... 뱃지도 그렇네요.. 굳이 만들 필요가 없겠군요. 무지에서 비롯된 issue였습니다 실례하였습니다... T T close 하겠습니다.

**Comment by marocchino** [comment]
이 이슈랑 상관없는 이야기라 죄송합니다만.. 뭐 번역하시나요?

요즘 좀뜸하긴한데 
https://github.com/nodeschool/seoul/issues/5
노드스쿨 관련 번역은 이쪽에서 하고있었습니다.

**Comment by eunsucking** [comment]
@marocchino 지금 how-to-npm 번역하고 있습니다.  오오 노드스쿨 번역 페이지도 잇군요! ㅋㅋ
