### ISSUE TITLE
소셜 미디어 관리 방안

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#6]
#3 에서 나누었습니다.

트위터 계정([@iojs_kr](https://twitter.com/iojs_kr))과 트위터로 인증하는 Medium 계정([@iojs_kr](https://medium.com/@iojs_kr))이 있습니다. 둘 다 일단 제 개인 메일에 +iojs를 붙인 계정에 연결했습니다.

이 분류에 남은 의제는 다음과 같습니다.

소셜 미디어 계정은 누구와 공유할 것인가.
1. 모두가 공유한다.
2. 소수 책임자만 공유한다.

**Comment by xarus01** [comment]
2가 좋겠습니다.
재고해본 결과 소셜 미디어 계정 자체가 모두에게 공유되는게 바람직한 상황 같지는 않네요.
하지만 맡고 계시는 분이 운영에 어려움을 겪는 경우 빠른 전환이 필요할 것 같습니다.

**Comment by nundefined** [comment]
저도 2번이 좋겠습니다.
소수로 해보고 다수에게 공유할 일이 필요하다면 그 때 가서
공유 범위를 넓혀도 좋겠습니다.

**Comment by taggon** [comment]
일단은 요청하신 분들께 백업도 겸해서 아이디와 패스워드를 공유해드렸습니다.
혹시 제가 못하게 되면 작업부탁드립니다.

가급적이면 발행을 자동화 할 수 있는 방법을 찾아보겠습니다. ^^;;
