### ISSUE TITLE
build setting

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#606]
1. lambci의 버전을 0.9.6 에서 0.9.13으로 업그레이드 해봤습니다.
혹시 문제 있으면 알려주세요.

2. pr에 마크다운 린트나 텍스트 린트를 넣어보는 건 어떨까요? -ㅁ-

**Comment by outsideris** [comment]
이쪽 커밋이 아니라 CI쪽에서 업그레이드 하셨다는 얘기시군요. 

2. 마크다운 린트는 한번도 안써봤는데 있으면 좋을거 같습니다. 텍스트 린트는 어떤거에요?

**Comment by outsideris** [comment]
제가 GitHub Actions 권한을 받아서인지 nodejs 에 권한이 생긴건지 몰라도 지금 nodejs-ko 저장소에는 Actions을 사용할 수 있는 메뉴가 나옵니다.(저만 보이는건 아니겠죠?)
Lambci가 @marocchino 님이 관리하셔야 해서 GitHub 액션이나 혹은 다른 CI로 옮겨 가는 것은 어떨까요?

**Comment by yous** [comment]
저도 Actions 탭이 보이네요. 관리만 편하다면 다른 것으로 넘어가도 좋을 것 같습니다.

**Comment by marocchino** [comment]
네 전혀상관없습니다.
어짜피 travis쓸수 있었으면 그쪽으로 했을거기도 하고.. 권한이 어떻게 될지 모르겠네요.

**Comment by outsideris** [comment]
#793 과도 연관된 이슈인데 Netlify를 이용하면 편하긴 할것 같은데 github page의 도메인은 못쓸것 같은 느낌이 듭니다. 일단 Action으로 테스트를 해보겠습니다.

**Comment by yous** [comment]
혹시 최근 빌드는 배포가 안 되고 있는 건가요? CI 설정으로 푸시만 하면 배포되도록 하는 게 제일 마음 편할 것 같네요.

**Comment by marocchino** [comment]
@yous npm의존성 문제 같네요. -ㅅ-

로컬에서 확인해봐도 같은 결과가 나옵니다.
버전 올려야 겠네영..
```
...
INFO  583 files generated in 23 s
INFO  Deploying: git
You have to configure the deployment settings in _config.yml first!

Example:
  deploy:
    type: git
    repo: <repository url>
    branch: [branch]
    message: [message]

    extend_dirs: [extend directory]

For more help, you can check the docs: http://hexo.io/docs/deployment.html
```

**Comment by yous** [comment]
`repo`를 지정해야 하는 것 같네요. `repo: https://github.com/nodejs/nodejs-ko` 추가하니 작동하는 것 같습니다.

**Comment by marocchino** [comment]
음.. 환경변수 넘기는 법이 바뀌었나.. 메뉴얼 다시한번 읽어볼꼐요.

**Comment by marocchino** [comment]
hexo-deployer-git에 [env로 repo를 넘기는 부분](https://github.com/hexojs/hexo-deployer-git/blob/master/lib/deployer.js#L29-L31)이 포함된 버전이 릴리즈가 안되서 마스터 보게 하고있었는데 업데이트하면서 이부분이 재대로 동작 안하게 된것 같습니다.

로그를 뒤져서 가장 마지막으로 성공했던 [로그](https://s3.amazonaws.com/lambci-buildresults-9ik0uityxxxc/gh/nodejs/nodejs-ko/builds/580/98f11b590c6cefe36dd0ac7e229e8f6f.html)확인해보니 
https://github.com/hexojs/hexo-deployer-git/commit/5e179c68dc40acd4a14d4761527124598496e03c 
까지는 정상 동작했었네요.
근데 11월 시점에도 최신 릴리즈가 0.2.0이라 버전으로 은 못하고, 일단 당장은 위에 커밋으로 고정시켜뒀다가 나중에 고쳐서 pr보내야겠습니다.

**Comment by outsideris** [comment]
빌드안되는 걸 모르고 있었군요. 저도 살펴보겠습니다.
