### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#677]
왠지 그룹에서 재거 됐네요. 😨 
<img width="679" alt="screen shot 2018-02-21 at 15 03 03" src="https://user-images.githubusercontent.com/128431/36465488-99d9064a-1718-11e8-96f5-336521dd1ce5.png">

2월2일 이었는데 늦게 발견했습니다. -ㅁ-

**Comment by outsideris** [comment]
앗 왜죠? 이거 ko-bot이 뭐에요? ci 봇인가요?

**Comment by marocchino** [comment]
네. deploy할때 쓰고있었습니다.

**Comment by marocchino** [comment]
이거 어쩔까요..
=ㅁ=;;

**Comment by freenice12** [comment]
이거슨 노드 파운데이션에서 아마도 2FA 이중 인증을 활성화 하지 않은 계정은 탈퇴 시켯기때문이 아닐까요? 얼마전 저도 제명당했다가ㅈ복구했습니다ㅡㅜ

**Comment by outsideris** [comment]
이슈 만들어봐야겠네요. 커뮤니티쪽이나 그쪽에 문의를 해보면 될것 같습니다.

**Comment by marocchino** [comment]
아 그렇군요.. 활성화시켜도 람다에서 훅넣을수있는지 확인해봐야겠네요.

**Comment by marocchino** [comment]
오늘 아침에 초대 받았습니다. #680 머지되고 ci도는거 확인되면 닫아도돼겠네요.

**Comment by outsideris** [comment]
이번에 머지할 때 CI가 잘 도는지 확인하도록 하겠습니다.

**Comment by marocchino** [comment]
https://lambci-buildresults-9ik0uityxxxc.s3.amazonaws.com/gh/nodejs/nodejs-ko/builds/430/3268a2a27a32c82ab4aa97e7ad2c8cf4.html
흑흑 퇴근하고나서 한번 봐야겠네요.

큐는 나가는데 빌드가 실패합니다.

**Comment by outsideris** [comment]
도와드리고 싶은데 전 lambci를 잘 모르겠네요 ㅠㅠ

**Comment by freenice12** [comment]
이번에도 빌드가 실패한것 같습니다.

**Comment by marocchino** [comment]
그냥 노드 버전 올리니 해결됐네요. 11484f0cd39b9b92fc18bbe53f7651e0a087bcd4 
도와주셔서 감사했습니다.
