### ISSUE TITLE
RSS->트위터 자동 발송 설정

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#79]

**Comment by taggon** [comment]
이거 제가 가져가도 될까요?

**Comment by outsideris** [comment]
네네 제가 한다고 하고는 계속 진행못했네요. 
참고로 몇일 전에 Github 페이지에 Jekyll Feeds가 추가되었습니다. https://github.com/blog/2053-easier-feeds-for-github-pages

**Comment by taggon** [comment]
10분마다 한 번씩 Jekyll의 피드를 확인해서 최신 글을 트윗하도록 작성했습니다.
소스 코드는 https://github.com/taggon/node_tweet_bot에 올려두었으니 혹시 개선할만한 점이 있다면 말씀해주셔도 좋습니다. 여기서만 쓸거라 딱히 설명같은 건 없습니다... 쿨럭...

**Comment by outsideris** [comment]
최근 트윗이 여길로 나온거였나 보군요. ㅎㅎ 수고하셨습니다. 이 봇은 개인 서버에 올려두신건가요?

**Comment by taggon** [comment]
@outsideris 네, 제 개인 서버에 올려뒀습니다. :)

**Comment by outsideris** [comment]
트윗을 보면 같은 글이 여러번 트윗되고 있습니다. 여럿이 관리하다 보니 좀 애매한데 다른 분이 직접 올리신게 아니라면 이미 올린 글에 대한 확인에 버그가 있지 않나 싶습니다. 확인부탁드립니다.

**Comment by taggon** [comment]
@outsideris 
이게 전에도 발생했는데 12시간마다 꼬박꼬박 발생하더군요.
10분마다 한 번씩 실행되는 프로그램인데 12시간마다 버그가 발생하다니... 로그를 한 번 남겨봐야겠습니다.

**Comment by outsideris** [comment]
저도 첨에는 누가 봇이 있는줄 모르고 직접하셨나 하다가 오늘 좀 많아졌길래 재오픈을 했습니다. 시간날때 저도 소스 좀 확인해 보겠습니다. 혹시 크래시나서 앱이 죽었다 올라오면 최신글을 다시 트윗하는건 아닐까요?

**Comment by taggon** [comment]
현재 가장 최종 버전을 3일째 운영 중인데 아직은 잘 되는 것 같습니다.
다음 게시글 업데이트까지 문제없이 동작하면 이 이슈 닫도록 하겠습니다.

**Comment by outsideris** [comment]
별 문제 없는것 같아서 닫습니다.
