### ISSUE TITLE
폴더와 파일 구성

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#8]
#3 에서 나누었습니다.

다음과 같은 형식을 제안합니다. 찬성 또는 다른 의견을 제시해주세요. :)
- 주간 뉴스  
  매주 금요일 발행되는 주간 뉴스는 `weekly/2015-02-06.md`와 같이 `weekly` 폴더 안에 파일 이름을 날짜로 유지했으면 합니다.
- 그 외  
  `articles` 폴더 안에 제목을 파일 이름으로 저장했으면 합니다. 예를 들어 [How io.js built a 146 person, 27 language localization effort… in one day.](https://medium.com/@mikeal/how-io-js-built-a-146-person-27-language-localization-effort-in-one-day-65e5b1c49a62) 이 글은 `how-io-js-built-a-146-person-27-language-localization-effort-in-one-day.md`가 되는 것이 좋다고 생각합니다.

**Comment by taggon** [comment]
@outsideris @hibiyasleep @xarus01 @nundefined 님의 의견 부탁드립니다.

**Comment by outsideris** [comment]
폴더명에는 이견이 없습니다.
다만 파일명은 제목을 파일명패턴으로 정규화해주는 어떤 정해진 방법이 있으면 좋겠다는 생각은 드네요.(물론 PR에서 관리할 수 있으므로 큰 문제는 아니긴 합니다.)

폴더에서 `weekly`랑 `articles`로 나누는걸 보니 생각난건데 저장소에서는 글을 탐색하기가 어려운데 jekyll같은 형식을 따라서 Page로 배포하는건 어떻게 생각하시나요?(Medium도 의견내서 자꾸 일을 늘려가는 느낌이 있긴 한데 아직 초기라 다양한 얘기가 오가고 있어서 던져봅니다.)

**Comment by nundefined** [comment]
폴더명 규칙에 찬성해요..

**Comment by taggon** [comment]
방법은 여러 가지를 시도해봐도 좋다고 생각합니다.
그런데 jekyll을 도입하려면 어떤 식으로 작업해야하는지 관리에 있어 있을 수도 있는 문제와 장점은 무엇이 있는지 알려주실 수 있을까요?
jekyll을 사용해 본 적이 없어서 판단이 잘 안되서요. :)

**Comment by outsideris** [comment]
저도 [Jekyll](http://jekyllrb-ko.github.io/)을 많이 써본 편은 아닙니다만 제 생각으로는 다음 정도입니다. 사용하려면 Github가 기본적으로 Jekyll을 제공하므로 [nolbool](https://github.com/nolboo/nolboo.github.io)처럼 폴더구조를 만들어서 포스트를 추가하면 됩니다.(적고 보니 좀 복잡해 보이긴 하네요.)

#### 장점
- github.io에서 Blog 처럼 제공할 수 있다.([Nolboo's blog](http://nolboo.github.io/) 참고)
- 원하는 테마를 사용할 수 있다.(Github 제공 스킨 뿐 아니라 Jekyll 테마 다수 존재)
- 정적페이지이지만 블로그처럼 글의 전체 목록이나 글간 이동등의 제공을 할 수 있다.

#### 단점
- Jekyll로 올리기 위해서 `gh-pages` 브랜치에 누군가 올려야 한다.(테스트 다시 해봐야 하는데 Project페이지라 `gh-pages`쪽 브랜치로 올려야 github.io로 배포될 겁니다. `gh-pages`를 메인 브랜치로 가져가는 방안도 있는데 이건 테스트나 확인을 좀 해봐야겠네요.)
- Jekyll의 폴더 관례를 어느정도 따라야 하고 PR을 보내는 사람도 이를 인지해야 한다.
- 각 글은 마크다운이긴 하지만 Jekyll에 대한 관례가 좀 필요하다(상단에 yaml로 제목이나 날짜, 카테고리등을 지정할 수 있습니다.)
- 정말 블로그처럼 제공하려면 Jekyll에 맞게 코딩을 좀 해야 한다.

**Comment by xarus01** [comment]
Jekyll 쓰면 좋을것 같습니다.  지금 번역을 해도 배포하는 곳이 부족한데 github 페이지를 이용하면 일단 배포할 곳이 비교적 간단하게 하나 늘어나고, 폴더 구조도 관련해서 정리할 수 있을 것 같네요.

**Comment by hibiyasleep** [comment]
Jekyll 찬성합니다.

**Comment by nundefined** [comment]
Jekyll 한 번 해보죠~

**Comment by outsideris** [comment]
찬성하신 분들이 여럿 계시니 일단 Jekyll 설정을 해보겠습니다.

**Comment by outsideris** [comment]
Jekyll이 자리잡았으므로 이슈를 닫습니다.
