### ISSUE TITLE
Conference?

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs-ko#81]
I went to Seoul a few years back for an amazing event!

I was wondering if anyone in Korea was planning on doing an event this year?

There is an event in Tokyo 11/7 or 11/8 https://twitter.com/nodefest/status/614383334915870720 and an event in Singapore http://2015.jsconf.asia/ on 11/19-20. If you did an event in between those I could easily stop by to speak and I could possibly help find some other traveling speakers as well :)

**Comment by outsideris** [comment]
@mikeal Oh!! good.
Actually, we have a plan for play.node this year again.(Just talk about it with some people in play.node a few years ago, not in iojs-ko yet.)
Good to know your schedule and I'm preparing to contact you.
I will talk to other guys about your good news.

**Comment by mikeal** [comment]
@outsideris awesome!
