### ISSUE TITLE
Introducing Node.js 12

### ISSUE THREAD

**Issue by outsideris** [nodejs/nodejs-ko#837]
https://medium.com/@nodejs/introducing-node-js-12-76c41a1b3f3f

미디엄 글이지만 메이저 버전이라 올려봤습니다.

**Comment by MiryangJung** [comment]
제가 번역을 해도될까요? :]

**Comment by outsideris** [comment]
@dalhav 네 하셔도 됩니다.

**Comment by yous** [comment]
@MiryangJung 혹시 작업 중이신가요?

**Comment by taggon** [comment]
번역이 이루어지지 않은 채 시간이 많이 지난데다가 벌써 1년쯤 지난 정보라서 굳이 번역하지 않아도 될 거라 생각합니다. 일단은 이슈 닫겠습니다.
