### ISSUE TITLE
label 실패

### ISSUE THREAD

**Issue by marocchino** [nodejs/nodejs-ko#876]
https://github.com/nodejs/nodejs-ko/pull/874#issuecomment-529195915

[토큰 문제](https://github.com/nodejs/nodejs-ko/settings/secrets)일거같은데 한번 삭제하고 다시작성해보겠습니다.

**Comment by marocchino** [comment]
https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret

**Comment by marocchino** [comment]
어드민 권한없는사람이 열면 실패한다고 합니다.

https://github.com/actions/labeler/issues/12#issuecomment-549534390

그냥 다시 손으로 할까요 =ㅅ=);

**Comment by yous** [comment]
일단 해결 방법이 나올 때까지 자동 label 지정은 빼고 해도 될 것 같네요.

**Comment by marocchino** [comment]
아 이거 까먹고 있었네요.
오늘 저녁에 크론으로 바꿔두겠습니다.
