### ISSUE TITLE
io.js 3.0.0 이 릴리즈 되었는데 공식 커뮤니티에 아직 번역글이 없어서 이슈로 남깁니다

### ISSUE THREAD

**Issue by kheyohsu** [nodejs/nodejs-ko#96]
https://github.com/nodejs/io.js/blob/master/CHANGELOG.md

제가 영어를 못해서 번역을 못하는데

아직 릴리즈 된 소식을 못들으신건지 하고 계신건지 몰라서

이슈를 남깁니다

번역기를 돌려서 번역을 해도 된다면

번역기를 돌리고 이상한 부분은 수작업으로 수정해서

올려볼려고 하는데 괜찮을까요?

**Comment by marocchino** [comment]
릴리스는 이번주차 주간뉴스에서 요약해서 언급이 있으리라 생각합니다.
올려주시는건 물론 괜찮습니다. :bow:

**Comment by yous** [comment]
안녕하세요, [#101](https://github.com/nodejs/iojs-ko/pull/101)에서 번역되었습니다. [8월 7일 뉴스](http://nodejs.github.io/iojs-ko/weekly/2015/08/07/weekly/)를 보시면 됩니다.
